// Auto-generated by scripts/generate-product-assets.mjs — do not edit manually
export interface ProductImagePair {
  thumbnail: string;
  full: string;
}

export interface ProductWattVariant {
  wattage: string;
  label: string;
  images: ProductImagePair[];
}

export interface ProductAssetEntry {
  listingThumbnail: string;
  wattVariants: ProductWattVariant[];
}

export const PRODUCT_ASSET_MANIFEST: Record<string, ProductAssetEntry> = {
  "spl-212": {
    "listingThumbnail": "/assets/AG - VEIL/Calm/SPL - 212 - PNG/SPL - 212 - 1&1/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "7W",
        "label": "7W",
        "images": [
          {
            "thumbnail": "/assets/AG - VEIL/Calm/SPL - 212 - PNG/SPL - 212 - 1&1/1-thumbnail.png",
            "full": "/assets/AG - VEIL/Calm/SPL - 212 - PNG/SPL - 212 - 1&1/1.png"
          },
          {
            "thumbnail": "/assets/AG - VEIL/Calm/SPL - 212 - PNG/SPL - 212 - 1&1/2-thumbnail.png",
            "full": "/assets/AG - VEIL/Calm/SPL - 212 - PNG/SPL - 212 - 1&1/2.png"
          },
          {
            "thumbnail": "/assets/AG - VEIL/Calm/SPL - 212 - PNG/SPL - 212 - 1&1/3-thumbnail.png",
            "full": "/assets/AG - VEIL/Calm/SPL - 212 - PNG/SPL - 212 - 1&1/3.png"
          }
        ]
      },
      {
        "wattage": "10W",
        "label": "10W",
        "images": [
          {
            "thumbnail": "/assets/AG - VEIL/Calm/SPL - 212 - PNG/SPL - 212 - 2ND - BK/1-thumbnail.png",
            "full": "/assets/AG - VEIL/Calm/SPL - 212 - PNG/SPL - 212 - 2ND - BK/1.png"
          },
          {
            "thumbnail": "/assets/AG - VEIL/Calm/SPL - 212 - PNG/SPL - 212 - 2ND - BK/2-thumbnail.png",
            "full": "/assets/AG - VEIL/Calm/SPL - 212 - PNG/SPL - 212 - 2ND - BK/2.png"
          },
          {
            "thumbnail": "/assets/AG - VEIL/Calm/SPL - 212 - PNG/SPL - 212 - 2ND - BK/3-thumbnail.png",
            "full": "/assets/AG - VEIL/Calm/SPL - 212 - PNG/SPL - 212 - 2ND - BK/3.png"
          }
        ]
      },
      {
        "wattage": "12W",
        "label": "12W",
        "images": [
          {
            "thumbnail": "/assets/AG - VEIL/Calm/SPL - 212 - PNG/SPL - 212 - 3RD - 12W/1-thumbnail.png",
            "full": "/assets/AG - VEIL/Calm/SPL - 212 - PNG/SPL - 212 - 3RD - 12W/1.png"
          },
          {
            "thumbnail": "/assets/AG - VEIL/Calm/SPL - 212 - PNG/SPL - 212 - 3RD - 12W/2-thumbnail.png",
            "full": "/assets/AG - VEIL/Calm/SPL - 212 - PNG/SPL - 212 - 3RD - 12W/2.png"
          },
          {
            "thumbnail": "/assets/AG - VEIL/Calm/SPL - 212 - PNG/SPL - 212 - 3RD - 12W/3-thumbnail.png",
            "full": "/assets/AG - VEIL/Calm/SPL - 212 - PNG/SPL - 212 - 3RD - 12W/3.png"
          }
        ]
      },
      {
        "wattage": "16W",
        "label": "16W",
        "images": [
          {
            "thumbnail": "/assets/AG - VEIL/Calm/SPL - 212 - PNG/SPL - 212 - 4TH - 16W/1-thumbnail.png",
            "full": "/assets/AG - VEIL/Calm/SPL - 212 - PNG/SPL - 212 - 4TH - 16W/1.png"
          },
          {
            "thumbnail": "/assets/AG - VEIL/Calm/SPL - 212 - PNG/SPL - 212 - 4TH - 16W/2-thumbnail.png",
            "full": "/assets/AG - VEIL/Calm/SPL - 212 - PNG/SPL - 212 - 4TH - 16W/2.png"
          },
          {
            "thumbnail": "/assets/AG - VEIL/Calm/SPL - 212 - PNG/SPL - 212 - 4TH - 16W/3-thumbnail.png",
            "full": "/assets/AG - VEIL/Calm/SPL - 212 - PNG/SPL - 212 - 4TH - 16W/3.png"
          }
        ]
      }
    ]
  },
  "spl-144": {
    "listingThumbnail": "/assets/AG - VEIL/Drape/SPL - 144 - PNG/SPL - 144 - 12(W)/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "12W",
        "label": "12W",
        "images": [
          {
            "thumbnail": "/assets/AG - VEIL/Drape/SPL - 144 - PNG/SPL - 144 - 12(W)/1-thumbnail.png",
            "full": "/assets/AG - VEIL/Drape/SPL - 144 - PNG/SPL - 144 - 12(W)/1.png"
          },
          {
            "thumbnail": "/assets/AG - VEIL/Drape/SPL - 144 - PNG/SPL - 144 - 12(W)/2-thumbnail.png",
            "full": "/assets/AG - VEIL/Drape/SPL - 144 - PNG/SPL - 144 - 12(W)/2.png"
          },
          {
            "thumbnail": "/assets/AG - VEIL/Drape/SPL - 144 - PNG/SPL - 144 - 12(W)/3-thumbnail.png",
            "full": "/assets/AG - VEIL/Drape/SPL - 144 - PNG/SPL - 144 - 12(W)/3.png"
          }
        ]
      }
    ]
  },
  "spl-214": {
    "listingThumbnail": "/assets/AG - VEIL/Dusk/SPL - 214 - PNG/SPL - 214 - 22W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "20W",
        "label": "20W",
        "images": [
          {
            "thumbnail": "/assets/AG - VEIL/Dusk/SPL - 214 - PNG/SPL - 214 - 22W/1-thumbnail.png",
            "full": "/assets/AG - VEIL/Dusk/SPL - 214 - PNG/SPL - 214 - 22W/1.png"
          },
          {
            "thumbnail": "/assets/AG - VEIL/Dusk/SPL - 214 - PNG/SPL - 214 - 22W/2-thumbnail.png",
            "full": "/assets/AG - VEIL/Dusk/SPL - 214 - PNG/SPL - 214 - 22W/2.png"
          },
          {
            "thumbnail": "/assets/AG - VEIL/Dusk/SPL - 214 - PNG/SPL - 214 - 22W/3-thumbnail.png",
            "full": "/assets/AG - VEIL/Dusk/SPL - 214 - PNG/SPL - 214 - 22W/3.png"
          }
        ]
      }
    ]
  },
  "spl-227": {
    "listingThumbnail": "/assets/AG - VEIL/Shade/SPL - 227 - PNG/SPL - 227 - 8W - WH/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "8W",
        "label": "8W",
        "images": [
          {
            "thumbnail": "/assets/AG - VEIL/Shade/SPL - 227 - PNG/SPL - 227 - 8W - WH/1-thumbnail.png",
            "full": "/assets/AG - VEIL/Shade/SPL - 227 - PNG/SPL - 227 - 8W - WH/1.png"
          },
          {
            "thumbnail": "/assets/AG - VEIL/Shade/SPL - 227 - PNG/SPL - 227 - 8W - WH/2-thumbnail.png",
            "full": "/assets/AG - VEIL/Shade/SPL - 227 - PNG/SPL - 227 - 8W - WH/2.png"
          },
          {
            "thumbnail": "/assets/AG - VEIL/Shade/SPL - 227 - PNG/SPL - 227 - 8W - WH/3-thumbnail.png",
            "full": "/assets/AG - VEIL/Shade/SPL - 227 - PNG/SPL - 227 - 8W - WH/3.png"
          }
        ]
      },
      {
        "wattage": "12W",
        "label": "12W",
        "images": [
          {
            "thumbnail": "/assets/AG - VEIL/Shade/SPL - 227 - PNG/SPL - 227 - 12W - BK/1-thumbnail.png",
            "full": "/assets/AG - VEIL/Shade/SPL - 227 - PNG/SPL - 227 - 12W - BK/1.png"
          },
          {
            "thumbnail": "/assets/AG - VEIL/Shade/SPL - 227 - PNG/SPL - 227 - 12W - BK/2-thumbnail.png",
            "full": "/assets/AG - VEIL/Shade/SPL - 227 - PNG/SPL - 227 - 12W - BK/2.png"
          },
          {
            "thumbnail": "/assets/AG - VEIL/Shade/SPL - 227 - PNG/SPL - 227 - 12W - BK/3-thumbnail.png",
            "full": "/assets/AG - VEIL/Shade/SPL - 227 - PNG/SPL - 227 - 12W - BK/3.png"
          }
        ]
      },
      {
        "wattage": "15W",
        "label": "15W",
        "images": [
          {
            "thumbnail": "/assets/AG - VEIL/Shade/SPL - 227 - PNG/SPL - 227 - 15W - WH/1-thumbnail.png",
            "full": "/assets/AG - VEIL/Shade/SPL - 227 - PNG/SPL - 227 - 15W - WH/1.png"
          },
          {
            "thumbnail": "/assets/AG - VEIL/Shade/SPL - 227 - PNG/SPL - 227 - 15W - WH/2-thumbnail.png",
            "full": "/assets/AG - VEIL/Shade/SPL - 227 - PNG/SPL - 227 - 15W - WH/2.png"
          },
          {
            "thumbnail": "/assets/AG - VEIL/Shade/SPL - 227 - PNG/SPL - 227 - 15W - WH/3-thumbnail.png",
            "full": "/assets/AG - VEIL/Shade/SPL - 227 - PNG/SPL - 227 - 15W - WH/3.png"
          }
        ]
      }
    ]
  },
  "arc": {
    "listingThumbnail": "/assets/CM - ORBIT/Arc/SPL - 48 - PNG/SPL - 48 - 12W - GOLD/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "12W",
        "label": "12W",
        "images": [
          {
            "thumbnail": "/assets/CM - ORBIT/Arc/SPL - 48 - PNG/SPL - 48 - 12W - GOLD/1-thumbnail.png",
            "full": "/assets/CM - ORBIT/Arc/SPL - 48 - PNG/SPL - 48 - 12W - GOLD/1.png"
          },
          {
            "thumbnail": "/assets/CM - ORBIT/Arc/SPL - 48 - PNG/SPL - 48 - 12W - GOLD/2-thumbnail.png",
            "full": "/assets/CM - ORBIT/Arc/SPL - 48 - PNG/SPL - 48 - 12W - GOLD/2.png"
          },
          {
            "thumbnail": "/assets/CM - ORBIT/Arc/SPL - 48 - PNG/SPL - 48 - 12W - GOLD/3-thumbnail.png",
            "full": "/assets/CM - ORBIT/Arc/SPL - 48 - PNG/SPL - 48 - 12W - GOLD/3.png"
          }
        ]
      }
    ]
  },
  "axis": {
    "listingThumbnail": "/assets/CM - ORBIT/Axis/SPL - 48 - PNG/SPL - 48 - 12W - GOLD/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "12W",
        "label": "12W",
        "images": [
          {
            "thumbnail": "/assets/CM - ORBIT/Axis/SPL - 48 - PNG/SPL - 48 - 12W - GOLD/1-thumbnail.png",
            "full": "/assets/CM - ORBIT/Axis/SPL - 48 - PNG/SPL - 48 - 12W - GOLD/1.png"
          },
          {
            "thumbnail": "/assets/CM - ORBIT/Axis/SPL - 48 - PNG/SPL - 48 - 12W - GOLD/2-thumbnail.png",
            "full": "/assets/CM - ORBIT/Axis/SPL - 48 - PNG/SPL - 48 - 12W - GOLD/2.png"
          },
          {
            "thumbnail": "/assets/CM - ORBIT/Axis/SPL - 48 - PNG/SPL - 48 - 12W - GOLD/3-thumbnail.png",
            "full": "/assets/CM - ORBIT/Axis/SPL - 48 - PNG/SPL - 48 - 12W - GOLD/3.png"
          }
        ]
      }
    ]
  },
  "flux": {
    "listingThumbnail": "/assets/CM - ORBIT/Flux/SPL - 166 - PNG/SPL - 166 - 8W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "8W",
        "label": "8W",
        "images": [
          {
            "thumbnail": "/assets/CM - ORBIT/Flux/SPL - 166 - PNG/SPL - 166 - 8W/1-thumbnail.png",
            "full": "/assets/CM - ORBIT/Flux/SPL - 166 - PNG/SPL - 166 - 8W/1.png"
          },
          {
            "thumbnail": "/assets/CM - ORBIT/Flux/SPL - 166 - PNG/SPL - 166 - 8W/2-thumbnail.png",
            "full": "/assets/CM - ORBIT/Flux/SPL - 166 - PNG/SPL - 166 - 8W/2.png"
          },
          {
            "thumbnail": "/assets/CM - ORBIT/Flux/SPL - 166 - PNG/SPL - 166 - 8W/3-thumbnail.png",
            "full": "/assets/CM - ORBIT/Flux/SPL - 166 - PNG/SPL - 166 - 8W/3.png"
          }
        ]
      }
    ]
  },
  "gyro": {
    "listingThumbnail": "/assets/CM - ORBIT/Gyro/SPL - 157 - PNG/SPL - 157 - WH - 6W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "6W",
        "label": "6W",
        "images": [
          {
            "thumbnail": "/assets/CM - ORBIT/Gyro/SPL - 157 - PNG/SPL - 157 - WH - 6W/1-thumbnail.png",
            "full": "/assets/CM - ORBIT/Gyro/SPL - 157 - PNG/SPL - 157 - WH - 6W/1.png"
          },
          {
            "thumbnail": "/assets/CM - ORBIT/Gyro/SPL - 157 - PNG/SPL - 157 - WH - 6W/2-thumbnail.png",
            "full": "/assets/CM - ORBIT/Gyro/SPL - 157 - PNG/SPL - 157 - WH - 6W/2.png"
          },
          {
            "thumbnail": "/assets/CM - ORBIT/Gyro/SPL - 157 - PNG/SPL - 157 - WH - 6W/3-thumbnail.png",
            "full": "/assets/CM - ORBIT/Gyro/SPL - 157 - PNG/SPL - 157 - WH - 6W/3.png"
          }
        ]
      }
    ]
  },
  "roam": {
    "listingThumbnail": "/assets/CM - ORBIT/Roam/SPL - 188 - PNG/SPL - 188 - BK - 8W3INL/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "8W",
        "label": "8W",
        "images": [
          {
            "thumbnail": "/assets/CM - ORBIT/Roam/SPL - 188 - PNG/SPL - 188 - BK - 8W3INL/1-thumbnail.png",
            "full": "/assets/CM - ORBIT/Roam/SPL - 188 - PNG/SPL - 188 - BK - 8W3INL/1.png"
          },
          {
            "thumbnail": "/assets/CM - ORBIT/Roam/SPL - 188 - PNG/SPL - 188 - BK - 8W3INL/2-thumbnail.png",
            "full": "/assets/CM - ORBIT/Roam/SPL - 188 - PNG/SPL - 188 - BK - 8W3INL/2.png"
          },
          {
            "thumbnail": "/assets/CM - ORBIT/Roam/SPL - 188 - PNG/SPL - 188 - BK - 8W3INL/3-thumbnail.png",
            "full": "/assets/CM - ORBIT/Roam/SPL - 188 - PNG/SPL - 188 - BK - 8W3INL/3.png"
          }
        ]
      }
    ]
  },
  "rover": {
    "listingThumbnail": "/assets/CM - ORBIT/Rover/SPL - 170 - PNG/SPL - 170 - 10W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "10W",
        "label": "10W",
        "images": [
          {
            "thumbnail": "/assets/CM - ORBIT/Rover/SPL - 170 - PNG/SPL - 170 - 10W/1-thumbnail.png",
            "full": "/assets/CM - ORBIT/Rover/SPL - 170 - PNG/SPL - 170 - 10W/1.png"
          },
          {
            "thumbnail": "/assets/CM - ORBIT/Rover/SPL - 170 - PNG/SPL - 170 - 10W/2-thumbnail.png",
            "full": "/assets/CM - ORBIT/Rover/SPL - 170 - PNG/SPL - 170 - 10W/2.png"
          },
          {
            "thumbnail": "/assets/CM - ORBIT/Rover/SPL - 170 - PNG/SPL - 170 - 10W/3-thumbnail.png",
            "full": "/assets/CM - ORBIT/Rover/SPL - 170 - PNG/SPL - 170 - 10W/3.png"
          }
        ]
      }
    ]
  },
  "swing": {
    "listingThumbnail": "/assets/CM - ORBIT/Swing/SPL - 83 - PNG/SPL - 83 - 6x3/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "6 x 3W",
        "label": "6 x 3W",
        "images": [
          {
            "thumbnail": "/assets/CM - ORBIT/Swing/SPL - 83 - PNG/SPL - 83 - 6x3/1-thumbnail.png",
            "full": "/assets/CM - ORBIT/Swing/SPL - 83 - PNG/SPL - 83 - 6x3/1.png"
          },
          {
            "thumbnail": "/assets/CM - ORBIT/Swing/SPL - 83 - PNG/SPL - 83 - 6x3/2-thumbnail.png",
            "full": "/assets/CM - ORBIT/Swing/SPL - 83 - PNG/SPL - 83 - 6x3/2.png"
          },
          {
            "thumbnail": "/assets/CM - ORBIT/Swing/SPL - 83 - PNG/SPL - 83 - 6x3/3-thumbnail.png",
            "full": "/assets/CM - ORBIT/Swing/SPL - 83 - PNG/SPL - 83 - 6x3/3.png"
          }
        ]
      }
    ]
  },
  "tilt": {
    "listingThumbnail": "/assets/CM - ORBIT/Tilt/SPL - 245 - PNG/SPL - 245 - 10W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "10W",
        "label": "10W",
        "images": [
          {
            "thumbnail": "/assets/CM - ORBIT/Tilt/SPL - 245 - PNG/SPL - 245 - 10W/1-thumbnail.png",
            "full": "/assets/CM - ORBIT/Tilt/SPL - 245 - PNG/SPL - 245 - 10W/1.png"
          },
          {
            "thumbnail": "/assets/CM - ORBIT/Tilt/SPL - 245 - PNG/SPL - 245 - 10W/2-thumbnail.png",
            "full": "/assets/CM - ORBIT/Tilt/SPL - 245 - PNG/SPL - 245 - 10W/2.png"
          },
          {
            "thumbnail": "/assets/CM - ORBIT/Tilt/SPL - 245 - PNG/SPL - 245 - 10W/3-thumbnail.png",
            "full": "/assets/CM - ORBIT/Tilt/SPL - 245 - PNG/SPL - 245 - 10W/3.png"
          }
        ]
      }
    ]
  },
  "traverse": {
    "listingThumbnail": "/assets/CM - ORBIT/Traverse/SPL - 174 - PNG/SPL - 174 - 8WGM/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "6W",
        "label": "6W",
        "images": [
          {
            "thumbnail": "/assets/CM - ORBIT/Traverse/SPL - 174 - PNG/SPL - 174 - 8WGM/1-thumbnail.png",
            "full": "/assets/CM - ORBIT/Traverse/SPL - 174 - PNG/SPL - 174 - 8WGM/1.png"
          },
          {
            "thumbnail": "/assets/CM - ORBIT/Traverse/SPL - 174 - PNG/SPL - 174 - 8WGM/2-thumbnail.png",
            "full": "/assets/CM - ORBIT/Traverse/SPL - 174 - PNG/SPL - 174 - 8WGM/2.png"
          },
          {
            "thumbnail": "/assets/CM - ORBIT/Traverse/SPL - 174 - PNG/SPL - 174 - 8WGM/3-thumbnail.png",
            "full": "/assets/CM - ORBIT/Traverse/SPL - 174 - PNG/SPL - 174 - 8WGM/3.png"
          }
        ]
      }
    ]
  },
  "vector": {
    "listingThumbnail": "/assets/CM - ORBIT/Vector/SPL - 232 - PNG/SPL - 232 - WH - 10W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "10W",
        "label": "10W",
        "images": [
          {
            "thumbnail": "/assets/CM - ORBIT/Vector/SPL - 232 - PNG/SPL - 232 - WH - 10W/1-thumbnail.png",
            "full": "/assets/CM - ORBIT/Vector/SPL - 232 - PNG/SPL - 232 - WH - 10W/1.png"
          },
          {
            "thumbnail": "/assets/CM - ORBIT/Vector/SPL - 232 - PNG/SPL - 232 - WH - 10W/2-thumbnail.png",
            "full": "/assets/CM - ORBIT/Vector/SPL - 232 - PNG/SPL - 232 - WH - 10W/2.png"
          },
          {
            "thumbnail": "/assets/CM - ORBIT/Vector/SPL - 232 - PNG/SPL - 232 - WH - 10W/3-thumbnail.png",
            "full": "/assets/CM - ORBIT/Vector/SPL - 232 - PNG/SPL - 232 - WH - 10W/3.png"
          }
        ]
      }
    ]
  },
  "brace": {
    "listingThumbnail": "/assets/DU - TWIN/Brace/SPL - 221 - PNG/SPL - 221 - 12x2/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "12 x 2W",
        "label": "12 x 2W",
        "images": [
          {
            "thumbnail": "/assets/DU - TWIN/Brace/SPL - 221 - PNG/SPL - 221 - 12x2/1-thumbnail.png",
            "full": "/assets/DU - TWIN/Brace/SPL - 221 - PNG/SPL - 221 - 12x2/1.png"
          },
          {
            "thumbnail": "/assets/DU - TWIN/Brace/SPL - 221 - PNG/SPL - 221 - 12x2/2-thumbnail.png",
            "full": "/assets/DU - TWIN/Brace/SPL - 221 - PNG/SPL - 221 - 12x2/2.png"
          },
          {
            "thumbnail": "/assets/DU - TWIN/Brace/SPL - 221 - PNG/SPL - 221 - 12x2/3-thumbnail.png",
            "full": "/assets/DU - TWIN/Brace/SPL - 221 - PNG/SPL - 221 - 12x2/3.png"
          }
        ]
      }
    ]
  },
  "double": {
    "listingThumbnail": "/assets/DU - TWIN/Double/SPL - 256 - PNG/SPL - 256 - 24W - WH+WH/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "12 x 2W",
        "label": "12 x 2W",
        "images": [
          {
            "thumbnail": "/assets/DU - TWIN/Double/SPL - 256 - PNG/SPL - 256 - 24W - WH+WH/1-thumbnail.png",
            "full": "/assets/DU - TWIN/Double/SPL - 256 - PNG/SPL - 256 - 24W - WH+WH/1.png"
          },
          {
            "thumbnail": "/assets/DU - TWIN/Double/SPL - 256 - PNG/SPL - 256 - 24W - WH+WH/2-thumbnail.png",
            "full": "/assets/DU - TWIN/Double/SPL - 256 - PNG/SPL - 256 - 24W - WH+WH/2.png"
          }
        ]
      }
    ]
  },
  "gemini": {
    "listingThumbnail": "/assets/DU - TWIN/Gemini/SPL - 220 - PNG/SPL - 220 - 10X2/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "12 x 2W",
        "label": "12 x 2W",
        "images": [
          {
            "thumbnail": "/assets/DU - TWIN/Gemini/SPL - 220 - PNG/SPL - 220 - 10X2/1-thumbnail.png",
            "full": "/assets/DU - TWIN/Gemini/SPL - 220 - PNG/SPL - 220 - 10X2/1.png"
          },
          {
            "thumbnail": "/assets/DU - TWIN/Gemini/SPL - 220 - PNG/SPL - 220 - 10X2/2-thumbnail.png",
            "full": "/assets/DU - TWIN/Gemini/SPL - 220 - PNG/SPL - 220 - 10X2/2.png"
          },
          {
            "thumbnail": "/assets/DU - TWIN/Gemini/SPL - 220 - PNG/SPL - 220 - 10X2/3-thumbnail.png",
            "full": "/assets/DU - TWIN/Gemini/SPL - 220 - PNG/SPL - 220 - 10X2/3.png"
          }
        ]
      },
      {
        "wattage": "18 x 2W",
        "label": "18 x 2W",
        "images": [
          {
            "thumbnail": "/assets/DU - TWIN/Gemini/SPL - 220 - PNG/SPL - 220 - 18X2/1-thumbnail.png",
            "full": "/assets/DU - TWIN/Gemini/SPL - 220 - PNG/SPL - 220 - 18X2/1.png"
          },
          {
            "thumbnail": "/assets/DU - TWIN/Gemini/SPL - 220 - PNG/SPL - 220 - 18X2/2-thumbnail.png",
            "full": "/assets/DU - TWIN/Gemini/SPL - 220 - PNG/SPL - 220 - 18X2/2.png"
          },
          {
            "thumbnail": "/assets/DU - TWIN/Gemini/SPL - 220 - PNG/SPL - 220 - 18X2/3-thumbnail.png",
            "full": "/assets/DU - TWIN/Gemini/SPL - 220 - PNG/SPL - 220 - 18X2/3.png"
          }
        ]
      }
    ]
  },
  "pair": {
    "listingThumbnail": "/assets/DU - TWIN/Pair/SPL - 250 - PNG/SPL - 250/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "12 x 2W",
        "label": "12 x 2W",
        "images": [
          {
            "thumbnail": "/assets/DU - TWIN/Pair/SPL - 250 - PNG/SPL - 250/1-thumbnail.png",
            "full": "/assets/DU - TWIN/Pair/SPL - 250 - PNG/SPL - 250/1.png"
          },
          {
            "thumbnail": "/assets/DU - TWIN/Pair/SPL - 250 - PNG/SPL - 250/2-thumbnail.png",
            "full": "/assets/DU - TWIN/Pair/SPL - 250 - PNG/SPL - 250/2.png"
          },
          {
            "thumbnail": "/assets/DU - TWIN/Pair/SPL - 250 - PNG/SPL - 250/3-thumbnail.png",
            "full": "/assets/DU - TWIN/Pair/SPL - 250 - PNG/SPL - 250/3.png"
          }
        ]
      }
    ]
  },
  "tandem": {
    "listingThumbnail": "/assets/DU - TWIN/Tandem/SPL - 196 - PNG/SPL - 196/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "20W",
        "label": "20W",
        "images": [
          {
            "thumbnail": "/assets/DU - TWIN/Tandem/SPL - 196 - PNG/SPL - 196/1-thumbnail.png",
            "full": "/assets/DU - TWIN/Tandem/SPL - 196 - PNG/SPL - 196/1.png"
          },
          {
            "thumbnail": "/assets/DU - TWIN/Tandem/SPL - 196 - PNG/SPL - 196/2-thumbnail.png",
            "full": "/assets/DU - TWIN/Tandem/SPL - 196 - PNG/SPL - 196/2.png"
          },
          {
            "thumbnail": "/assets/DU - TWIN/Tandem/SPL - 196 - PNG/SPL - 196/3-thumbnail.png",
            "full": "/assets/DU - TWIN/Tandem/SPL - 196 - PNG/SPL - 196/3.png"
          }
        ]
      }
    ]
  },
  "twice": {
    "listingThumbnail": "/assets/DU - TWIN/Twice/SPL - 222 - PNG/SPL - 222/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "12 x 2W",
        "label": "12 x 2W",
        "images": [
          {
            "thumbnail": "/assets/DU - TWIN/Twice/SPL - 222 - PNG/SPL - 222/1-thumbnail.png",
            "full": "/assets/DU - TWIN/Twice/SPL - 222 - PNG/SPL - 222/1.png"
          },
          {
            "thumbnail": "/assets/DU - TWIN/Twice/SPL - 222 - PNG/SPL - 222/2-thumbnail.png",
            "full": "/assets/DU - TWIN/Twice/SPL - 222 - PNG/SPL - 222/2.png"
          },
          {
            "thumbnail": "/assets/DU - TWIN/Twice/SPL - 222 - PNG/SPL - 222/3-thumbnail.png",
            "full": "/assets/DU - TWIN/Twice/SPL - 222 - PNG/SPL - 222/3.png"
          }
        ]
      }
    ]
  },
  "clasp": {
    "listingThumbnail": "/assets/FR - LATCH/Clasp/SPL - 228 - PNG/SPL - 228 - 12W - W+W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "12W",
        "label": "12W",
        "images": [
          {
            "thumbnail": "/assets/FR - LATCH/Clasp/SPL - 228 - PNG/SPL - 228 - 12W - W+W/1-thumbnail.png",
            "full": "/assets/FR - LATCH/Clasp/SPL - 228 - PNG/SPL - 228 - 12W - W+W/1.png"
          },
          {
            "thumbnail": "/assets/FR - LATCH/Clasp/SPL - 228 - PNG/SPL - 228 - 12W - W+W/2-thumbnail.png",
            "full": "/assets/FR - LATCH/Clasp/SPL - 228 - PNG/SPL - 228 - 12W - W+W/2.png"
          },
          {
            "thumbnail": "/assets/FR - LATCH/Clasp/SPL - 228 - PNG/SPL - 228 - 12W - W+W/3-thumbnail.png",
            "full": "/assets/FR - LATCH/Clasp/SPL - 228 - PNG/SPL - 228 - 12W - W+W/3.png"
          }
        ]
      },
      {
        "wattage": "18W",
        "label": "18W",
        "images": [
          {
            "thumbnail": "/assets/FR - LATCH/Clasp/SPL - 228 - PNG/SPL - 228 - 12 - W+W/1-thumbnail.png",
            "full": "/assets/FR - LATCH/Clasp/SPL - 228 - PNG/SPL - 228 - 12 - W+W/1.png"
          },
          {
            "thumbnail": "/assets/FR - LATCH/Clasp/SPL - 228 - PNG/SPL - 228 - 12 - W+W/2-thumbnail.png",
            "full": "/assets/FR - LATCH/Clasp/SPL - 228 - PNG/SPL - 228 - 12 - W+W/2.png"
          },
          {
            "thumbnail": "/assets/FR - LATCH/Clasp/SPL - 228 - PNG/SPL - 228 - 12 - W+W/3-thumbnail.png",
            "full": "/assets/FR - LATCH/Clasp/SPL - 228 - PNG/SPL - 228 - 12 - W+W/3.png"
          }
        ]
      }
    ]
  },
  "click": {
    "listingThumbnail": "/assets/FR - LATCH/Click/SPL - 252 - PNG/SPL - 252 - 18W - WH3INL/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "18W",
        "label": "18W",
        "images": [
          {
            "thumbnail": "/assets/FR - LATCH/Click/SPL - 252 - PNG/SPL - 252 - 18W - WH3INL/1-thumbnail.png",
            "full": "/assets/FR - LATCH/Click/SPL - 252 - PNG/SPL - 252 - 18W - WH3INL/1.png"
          },
          {
            "thumbnail": "/assets/FR - LATCH/Click/SPL - 252 - PNG/SPL - 252 - 18W - WH3INL/2-thumbnail.png",
            "full": "/assets/FR - LATCH/Click/SPL - 252 - PNG/SPL - 252 - 18W - WH3INL/2.png"
          },
          {
            "thumbnail": "/assets/FR - LATCH/Click/SPL - 252 - PNG/SPL - 252 - 18W - WH3INL/3-thumbnail.png",
            "full": "/assets/FR - LATCH/Click/SPL - 252 - PNG/SPL - 252 - 18W - WH3INL/3.png"
          }
        ]
      }
    ]
  },
  "hinge": {
    "listingThumbnail": "/assets/FR - LATCH/Hinge/SPL - 230 - PNG/SPL - 230 - 12W - WH/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "12W",
        "label": "12W",
        "images": [
          {
            "thumbnail": "/assets/FR - LATCH/Hinge/SPL - 230 - PNG/SPL - 230 - 12W - WH/1-thumbnail.png",
            "full": "/assets/FR - LATCH/Hinge/SPL - 230 - PNG/SPL - 230 - 12W - WH/1.png"
          },
          {
            "thumbnail": "/assets/FR - LATCH/Hinge/SPL - 230 - PNG/SPL - 230 - 12W - WH/2-thumbnail.png",
            "full": "/assets/FR - LATCH/Hinge/SPL - 230 - PNG/SPL - 230 - 12W - WH/2.png"
          },
          {
            "thumbnail": "/assets/FR - LATCH/Hinge/SPL - 230 - PNG/SPL - 230 - 12W - WH/3-thumbnail.png",
            "full": "/assets/FR - LATCH/Hinge/SPL - 230 - PNG/SPL - 230 - 12W - WH/3.png"
          }
        ]
      }
    ]
  },
  "open": {
    "listingThumbnail": "/assets/FR - LATCH/Open/SPL - 242 - PNG/SPL - 242 - 15W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "15W",
        "label": "15W",
        "images": [
          {
            "thumbnail": "/assets/FR - LATCH/Open/SPL - 242 - PNG/SPL - 242 - 15W/1-thumbnail.png",
            "full": "/assets/FR - LATCH/Open/SPL - 242 - PNG/SPL - 242 - 15W/1.png"
          },
          {
            "thumbnail": "/assets/FR - LATCH/Open/SPL - 242 - PNG/SPL - 242 - 15W/2-thumbnail.png",
            "full": "/assets/FR - LATCH/Open/SPL - 242 - PNG/SPL - 242 - 15W/2.png"
          },
          {
            "thumbnail": "/assets/FR - LATCH/Open/SPL - 242 - PNG/SPL - 242 - 15W/3-thumbnail.png",
            "full": "/assets/FR - LATCH/Open/SPL - 242 - PNG/SPL - 242 - 15W/3.png"
          }
        ]
      }
    ]
  },
  "snap": {
    "listingThumbnail": "/assets/FR - LATCH/Snap/SPL - 172 - PNG/SPL - 172 - 8W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "8W",
        "label": "8W",
        "images": [
          {
            "thumbnail": "/assets/FR - LATCH/Snap/SPL - 172 - PNG/SPL - 172 - 8W/1-thumbnail.png",
            "full": "/assets/FR - LATCH/Snap/SPL - 172 - PNG/SPL - 172 - 8W/1.png"
          },
          {
            "thumbnail": "/assets/FR - LATCH/Snap/SPL - 172 - PNG/SPL - 172 - 8W/2-thumbnail.png",
            "full": "/assets/FR - LATCH/Snap/SPL - 172 - PNG/SPL - 172 - 8W/2.png"
          },
          {
            "thumbnail": "/assets/FR - LATCH/Snap/SPL - 172 - PNG/SPL - 172 - 8W/3-thumbnail.png",
            "full": "/assets/FR - LATCH/Snap/SPL - 172 - PNG/SPL - 172 - 8W/3.png"
          }
        ]
      }
    ]
  },
  "alto": {
    "listingThumbnail": "/assets/GN - LUXE/Alto/SPL - 215 - PNG/SPL - 215 - 8W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "8W",
        "label": "8W",
        "images": [
          {
            "thumbnail": "/assets/GN - LUXE/Alto/SPL - 215 - PNG/SPL - 215 - 8W/1-thumbnail.png",
            "full": "/assets/GN - LUXE/Alto/SPL - 215 - PNG/SPL - 215 - 8W/1.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Alto/SPL - 215 - PNG/SPL - 215 - 8W/2-thumbnail.png",
            "full": "/assets/GN - LUXE/Alto/SPL - 215 - PNG/SPL - 215 - 8W/2.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Alto/SPL - 215 - PNG/SPL - 215 - 8W/3-thumbnail.png",
            "full": "/assets/GN - LUXE/Alto/SPL - 215 - PNG/SPL - 215 - 8W/3.png"
          }
        ]
      },
      {
        "wattage": "12W",
        "label": "12W",
        "images": [
          {
            "thumbnail": "/assets/GN - LUXE/Alto/SPL - 215 - PNG/SPL - 215 - 12W/1-thumbnail.png",
            "full": "/assets/GN - LUXE/Alto/SPL - 215 - PNG/SPL - 215 - 12W/1.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Alto/SPL - 215 - PNG/SPL - 215 - 12W/2-thumbnail.png",
            "full": "/assets/GN - LUXE/Alto/SPL - 215 - PNG/SPL - 215 - 12W/2.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Alto/SPL - 215 - PNG/SPL - 215 - 12W/3-thumbnail.png",
            "full": "/assets/GN - LUXE/Alto/SPL - 215 - PNG/SPL - 215 - 12W/3.png"
          }
        ]
      },
      {
        "wattage": "18W",
        "label": "18W",
        "images": [
          {
            "thumbnail": "/assets/GN - LUXE/Alto/SPL - 215 - PNG/SPL - 215 - 15W/1-thumbnail.png",
            "full": "/assets/GN - LUXE/Alto/SPL - 215 - PNG/SPL - 215 - 15W/1.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Alto/SPL - 215 - PNG/SPL - 215 - 15W/2-thumbnail.png",
            "full": "/assets/GN - LUXE/Alto/SPL - 215 - PNG/SPL - 215 - 15W/2.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Alto/SPL - 215 - PNG/SPL - 215 - 15W/3-thumbnail.png",
            "full": "/assets/GN - LUXE/Alto/SPL - 215 - PNG/SPL - 215 - 15W/3.png"
          }
        ]
      }
    ]
  },
  "crest": {
    "listingThumbnail": "/assets/GN - LUXE/Crest/SPL - 164 - PNG/SPL - 164 - 8W - BK/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "8W",
        "label": "8W",
        "images": [
          {
            "thumbnail": "/assets/GN - LUXE/Crest/SPL - 164 - PNG/SPL - 164 - 8W - BK/1-thumbnail.png",
            "full": "/assets/GN - LUXE/Crest/SPL - 164 - PNG/SPL - 164 - 8W - BK/1.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Crest/SPL - 164 - PNG/SPL - 164 - 8W - BK/2-thumbnail.png",
            "full": "/assets/GN - LUXE/Crest/SPL - 164 - PNG/SPL - 164 - 8W - BK/2.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Crest/SPL - 164 - PNG/SPL - 164 - 8W - BK/3-thumbnail.png",
            "full": "/assets/GN - LUXE/Crest/SPL - 164 - PNG/SPL - 164 - 8W - BK/3.png"
          }
        ]
      }
    ]
  },
  "lume": {
    "listingThumbnail": "/assets/GN - LUXE/Lume/SPL - 224 - PNG/SPL - 224 - 7W - WH/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "7W",
        "label": "7W",
        "images": [
          {
            "thumbnail": "/assets/GN - LUXE/Lume/SPL - 224 - PNG/SPL - 224 - 7W - WH/1-thumbnail.png",
            "full": "/assets/GN - LUXE/Lume/SPL - 224 - PNG/SPL - 224 - 7W - WH/1.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Lume/SPL - 224 - PNG/SPL - 224 - 7W - WH/2-thumbnail.png",
            "full": "/assets/GN - LUXE/Lume/SPL - 224 - PNG/SPL - 224 - 7W - WH/2.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Lume/SPL - 224 - PNG/SPL - 224 - 7W - WH/3-thumbnail.png",
            "full": "/assets/GN - LUXE/Lume/SPL - 224 - PNG/SPL - 224 - 7W - WH/3.png"
          }
        ]
      },
      {
        "wattage": "12W",
        "label": "12W",
        "images": [
          {
            "thumbnail": "/assets/GN - LUXE/Lume/SPL - 224 - PNG/SPL - 224 - 12W - BK/1-thumbnail.png",
            "full": "/assets/GN - LUXE/Lume/SPL - 224 - PNG/SPL - 224 - 12W - BK/1.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Lume/SPL - 224 - PNG/SPL - 224 - 12W - BK/2-thumbnail.png",
            "full": "/assets/GN - LUXE/Lume/SPL - 224 - PNG/SPL - 224 - 12W - BK/2.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Lume/SPL - 224 - PNG/SPL - 224 - 12W - BK/3-thumbnail.png",
            "full": "/assets/GN - LUXE/Lume/SPL - 224 - PNG/SPL - 224 - 12W - BK/3.png"
          }
        ]
      },
      {
        "wattage": "15W",
        "label": "15W",
        "images": [
          {
            "thumbnail": "/assets/GN - LUXE/Lume/SPL - 224 - PNG/SPL - 224 - 15W - 40 LD/1-thumbnail.png",
            "full": "/assets/GN - LUXE/Lume/SPL - 224 - PNG/SPL - 224 - 15W - 40 LD/1.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Lume/SPL - 224 - PNG/SPL - 224 - 15W - 40 LD/2-thumbnail.png",
            "full": "/assets/GN - LUXE/Lume/SPL - 224 - PNG/SPL - 224 - 15W - 40 LD/2.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Lume/SPL - 224 - PNG/SPL - 224 - 15W - 40 LD/3-thumbnail.png",
            "full": "/assets/GN - LUXE/Lume/SPL - 224 - PNG/SPL - 224 - 15W - 40 LD/3.png"
          }
        ]
      },
      {
        "wattage": "18W",
        "label": "18W",
        "images": [
          {
            "thumbnail": "/assets/GN - LUXE/Lume/SPL - 224 - PNG/SPL - 224 - 18W - WH/1-thumbnail.png",
            "full": "/assets/GN - LUXE/Lume/SPL - 224 - PNG/SPL - 224 - 18W - WH/1.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Lume/SPL - 224 - PNG/SPL - 224 - 18W - WH/2-thumbnail.png",
            "full": "/assets/GN - LUXE/Lume/SPL - 224 - PNG/SPL - 224 - 18W - WH/2.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Lume/SPL - 224 - PNG/SPL - 224 - 18W - WH/3-thumbnail.png",
            "full": "/assets/GN - LUXE/Lume/SPL - 224 - PNG/SPL - 224 - 18W - WH/3.png"
          }
        ]
      }
    ]
  },
  "prime": {
    "listingThumbnail": "/assets/GN - LUXE/Prime/SPL - 223 - PNG/SPL - 223 - 7W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "7W",
        "label": "7W",
        "images": [
          {
            "thumbnail": "/assets/GN - LUXE/Prime/SPL - 223 - PNG/SPL - 223 - 7W/1-thumbnail.png",
            "full": "/assets/GN - LUXE/Prime/SPL - 223 - PNG/SPL - 223 - 7W/1.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Prime/SPL - 223 - PNG/SPL - 223 - 7W/2-thumbnail.png",
            "full": "/assets/GN - LUXE/Prime/SPL - 223 - PNG/SPL - 223 - 7W/2.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Prime/SPL - 223 - PNG/SPL - 223 - 7W/3-thumbnail.png",
            "full": "/assets/GN - LUXE/Prime/SPL - 223 - PNG/SPL - 223 - 7W/3.png"
          }
        ]
      },
      {
        "wattage": "12W",
        "label": "12W",
        "images": [
          {
            "thumbnail": "/assets/GN - LUXE/Prime/SPL - 223 - PNG/SPL - 223 - 12W - S.B/1-thumbnail.png",
            "full": "/assets/GN - LUXE/Prime/SPL - 223 - PNG/SPL - 223 - 12W - S.B/1.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Prime/SPL - 223 - PNG/SPL - 223 - 12W - S.B/2-thumbnail.png",
            "full": "/assets/GN - LUXE/Prime/SPL - 223 - PNG/SPL - 223 - 12W - S.B/2.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Prime/SPL - 223 - PNG/SPL - 223 - 12W - S.B/3-thumbnail.png",
            "full": "/assets/GN - LUXE/Prime/SPL - 223 - PNG/SPL - 223 - 12W - S.B/3.png"
          }
        ]
      },
      {
        "wattage": "15W",
        "label": "15W",
        "images": [
          {
            "thumbnail": "/assets/GN - LUXE/Prime/SPL - 223 - PNG/SPL - 223 - 15W - BK/1-thumbnail.png",
            "full": "/assets/GN - LUXE/Prime/SPL - 223 - PNG/SPL - 223 - 15W - BK/1.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Prime/SPL - 223 - PNG/SPL - 223 - 15W - BK/2-thumbnail.png",
            "full": "/assets/GN - LUXE/Prime/SPL - 223 - PNG/SPL - 223 - 15W - BK/2.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Prime/SPL - 223 - PNG/SPL - 223 - 15W - BK/3-thumbnail.png",
            "full": "/assets/GN - LUXE/Prime/SPL - 223 - PNG/SPL - 223 - 15W - BK/3.png"
          }
        ]
      },
      {
        "wattage": "18W",
        "label": "18W",
        "images": [
          {
            "thumbnail": "/assets/GN - LUXE/Prime/SPL - 223 - PNG/SPL - 223 - 18W - WH/1-thumbnail.png",
            "full": "/assets/GN - LUXE/Prime/SPL - 223 - PNG/SPL - 223 - 18W - WH/1.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Prime/SPL - 223 - PNG/SPL - 223 - 18W - WH/2-thumbnail.png",
            "full": "/assets/GN - LUXE/Prime/SPL - 223 - PNG/SPL - 223 - 18W - WH/2.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Prime/SPL - 223 - PNG/SPL - 223 - 18W - WH/3-thumbnail.png",
            "full": "/assets/GN - LUXE/Prime/SPL - 223 - PNG/SPL - 223 - 18W - WH/3.png"
          }
        ]
      }
    ]
  },
  "vero": {
    "listingThumbnail": "/assets/GN - LUXE/Vero/SPL - 210 - PNG/SPL - 210 - 12W WTBK/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "12W",
        "label": "12W",
        "images": [
          {
            "thumbnail": "/assets/GN - LUXE/Vero/SPL - 210 - PNG/SPL - 210 - 12W WTBK/1-thumbnail.png",
            "full": "/assets/GN - LUXE/Vero/SPL - 210 - PNG/SPL - 210 - 12W WTBK/1.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Vero/SPL - 210 - PNG/SPL - 210 - 12W WTBK/2-thumbnail.png",
            "full": "/assets/GN - LUXE/Vero/SPL - 210 - PNG/SPL - 210 - 12W WTBK/2.png"
          },
          {
            "thumbnail": "/assets/GN - LUXE/Vero/SPL - 210 - PNG/SPL - 210 - 12W WTBK/3-thumbnail.png",
            "full": "/assets/GN - LUXE/Vero/SPL - 210 - PNG/SPL - 210 - 12W WTBK/3.png"
          }
        ]
      }
    ]
  },
  "surge": {
    "listingThumbnail": "/assets/HW - FORTE/Surge/SPL - 216 - PNG/SPL - 216 - 30W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "32W",
        "label": "32W",
        "images": [
          {
            "thumbnail": "/assets/HW - FORTE/Surge/SPL - 216 - PNG/SPL - 216 - 30W/1-thumbnail.png",
            "full": "/assets/HW - FORTE/Surge/SPL - 216 - PNG/SPL - 216 - 30W/1.png"
          },
          {
            "thumbnail": "/assets/HW - FORTE/Surge/SPL - 216 - PNG/SPL - 216 - 30W/2-thumbnail.png",
            "full": "/assets/HW - FORTE/Surge/SPL - 216 - PNG/SPL - 216 - 30W/2.png"
          },
          {
            "thumbnail": "/assets/HW - FORTE/Surge/SPL - 216 - PNG/SPL - 216 - 30W/3-thumbnail.png",
            "full": "/assets/HW - FORTE/Surge/SPL - 216 - PNG/SPL - 216 - 30W/3.png"
          }
        ]
      }
    ]
  },
  "titan": {
    "listingThumbnail": "/assets/HW - FORTE/Titan/SPL - 217 - PNG/SPL - 217 - 30W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "30W",
        "label": "30W",
        "images": [
          {
            "thumbnail": "/assets/HW - FORTE/Titan/SPL - 217 - PNG/SPL - 217 - 30W/1-thumbnail.png",
            "full": "/assets/HW - FORTE/Titan/SPL - 217 - PNG/SPL - 217 - 30W/1.png"
          },
          {
            "thumbnail": "/assets/HW - FORTE/Titan/SPL - 217 - PNG/SPL - 217 - 30W/2-thumbnail.png",
            "full": "/assets/HW - FORTE/Titan/SPL - 217 - PNG/SPL - 217 - 30W/2.png"
          },
          {
            "thumbnail": "/assets/HW - FORTE/Titan/SPL - 217 - PNG/SPL - 217 - 30W/3-thumbnail.png",
            "full": "/assets/HW - FORTE/Titan/SPL - 217 - PNG/SPL - 217 - 30W/3.png"
          }
        ]
      }
    ]
  },
  "disc": {
    "listingThumbnail": "/assets/LH - SLATE/Disc/SPL - 167 - PNG/SPL - 167 - 03IML/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "SPL - 167 - 03IML",
        "label": "SPL - 167 - 03IML",
        "images": [
          {
            "thumbnail": "/assets/LH - SLATE/Disc/SPL - 167 - PNG/SPL - 167 - 03IML/1-thumbnail.png",
            "full": "/assets/LH - SLATE/Disc/SPL - 167 - PNG/SPL - 167 - 03IML/1.png"
          },
          {
            "thumbnail": "/assets/LH - SLATE/Disc/SPL - 167 - PNG/SPL - 167 - 03IML/2-thumbnail.png",
            "full": "/assets/LH - SLATE/Disc/SPL - 167 - PNG/SPL - 167 - 03IML/2.png"
          },
          {
            "thumbnail": "/assets/LH - SLATE/Disc/SPL - 167 - PNG/SPL - 167 - 03IML/3-thumbnail.png",
            "full": "/assets/LH - SLATE/Disc/SPL - 167 - PNG/SPL - 167 - 03IML/3.png"
          }
        ]
      }
    ]
  },
  "ledge": {
    "listingThumbnail": "/assets/LH - SLATE/Ledge/SPL - 226 - PNG/SPL - 226 - 8W - W+SB/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "8W",
        "label": "8W",
        "images": [
          {
            "thumbnail": "/assets/LH - SLATE/Ledge/SPL - 226 - PNG/SPL - 226 - 8W - W+SB/1-thumbnail.png",
            "full": "/assets/LH - SLATE/Ledge/SPL - 226 - PNG/SPL - 226 - 8W - W+SB/1.png"
          },
          {
            "thumbnail": "/assets/LH - SLATE/Ledge/SPL - 226 - PNG/SPL - 226 - 8W - W+SB/2-thumbnail.png",
            "full": "/assets/LH - SLATE/Ledge/SPL - 226 - PNG/SPL - 226 - 8W - W+SB/2.png"
          },
          {
            "thumbnail": "/assets/LH - SLATE/Ledge/SPL - 226 - PNG/SPL - 226 - 8W - W+SB/3-thumbnail.png",
            "full": "/assets/LH - SLATE/Ledge/SPL - 226 - PNG/SPL - 226 - 8W - W+SB/3.png"
          }
        ]
      },
      {
        "wattage": "12W",
        "label": "12W",
        "images": [
          {
            "thumbnail": "/assets/LH - SLATE/Ledge/SPL - 226 - PNG/SPL - 226 - 12W - BK/1-thumbnail.png",
            "full": "/assets/LH - SLATE/Ledge/SPL - 226 - PNG/SPL - 226 - 12W - BK/1.png"
          },
          {
            "thumbnail": "/assets/LH - SLATE/Ledge/SPL - 226 - PNG/SPL - 226 - 12W - BK/2-thumbnail.png",
            "full": "/assets/LH - SLATE/Ledge/SPL - 226 - PNG/SPL - 226 - 12W - BK/2.png"
          },
          {
            "thumbnail": "/assets/LH - SLATE/Ledge/SPL - 226 - PNG/SPL - 226 - 12W - BK/3-thumbnail.png",
            "full": "/assets/LH - SLATE/Ledge/SPL - 226 - PNG/SPL - 226 - 12W - BK/3.png"
          }
        ]
      },
      {
        "wattage": "18W",
        "label": "18W",
        "images": [
          {
            "thumbnail": "/assets/LH - SLATE/Ledge/SPL - 226 - PNG/SPL - 226 - 18W - WH/1-thumbnail.png",
            "full": "/assets/LH - SLATE/Ledge/SPL - 226 - PNG/SPL - 226 - 18W - WH/1.png"
          },
          {
            "thumbnail": "/assets/LH - SLATE/Ledge/SPL - 226 - PNG/SPL - 226 - 18W - WH/2-thumbnail.png",
            "full": "/assets/LH - SLATE/Ledge/SPL - 226 - PNG/SPL - 226 - 18W - WH/2.png"
          },
          {
            "thumbnail": "/assets/LH - SLATE/Ledge/SPL - 226 - PNG/SPL - 226 - 18W - WH/3-thumbnail.png",
            "full": "/assets/LH - SLATE/Ledge/SPL - 226 - PNG/SPL - 226 - 18W - WH/3.png"
          }
        ]
      }
    ]
  },
  "shim": {
    "listingThumbnail": "/assets/LH - SLATE/Shim/SPL - 162 - PNG/SPL - 162 - WH - 12W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "12W",
        "label": "12W",
        "images": [
          {
            "thumbnail": "/assets/LH - SLATE/Shim/SPL - 162 - PNG/SPL - 162 - WH - 12W/1-thumbnail.png",
            "full": "/assets/LH - SLATE/Shim/SPL - 162 - PNG/SPL - 162 - WH - 12W/1.png"
          },
          {
            "thumbnail": "/assets/LH - SLATE/Shim/SPL - 162 - PNG/SPL - 162 - WH - 12W/2-thumbnail.png",
            "full": "/assets/LH - SLATE/Shim/SPL - 162 - PNG/SPL - 162 - WH - 12W/2.png"
          },
          {
            "thumbnail": "/assets/LH - SLATE/Shim/SPL - 162 - PNG/SPL - 162 - WH - 12W/3-thumbnail.png",
            "full": "/assets/LH - SLATE/Shim/SPL - 162 - PNG/SPL - 162 - WH - 12W/3.png"
          }
        ]
      }
    ]
  },
  "slab": {
    "listingThumbnail": "/assets/LH - SLATE/Slab/SPL - 192 - PNG/SPL - 192 - 15W - BK.H.V/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "15W",
        "label": "15W",
        "images": [
          {
            "thumbnail": "/assets/LH - SLATE/Slab/SPL - 192 - PNG/SPL - 192 - 15W - BK.H.V/1-thumbnail.png",
            "full": "/assets/LH - SLATE/Slab/SPL - 192 - PNG/SPL - 192 - 15W - BK.H.V/1.png"
          },
          {
            "thumbnail": "/assets/LH - SLATE/Slab/SPL - 192 - PNG/SPL - 192 - 15W - BK.H.V/2-thumbnail.png",
            "full": "/assets/LH - SLATE/Slab/SPL - 192 - PNG/SPL - 192 - 15W - BK.H.V/2.png"
          },
          {
            "thumbnail": "/assets/LH - SLATE/Slab/SPL - 192 - PNG/SPL - 192 - 15W - BK.H.V/3-thumbnail.png",
            "full": "/assets/LH - SLATE/Slab/SPL - 192 - PNG/SPL - 192 - 15W - BK.H.V/3.png"
          }
        ]
      }
    ]
  },
  "trim": {
    "listingThumbnail": "/assets/LH - SLATE/Trim/SPL - 254 - PNG/SPL - 254 - 18W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "18W",
        "label": "18W",
        "images": [
          {
            "thumbnail": "/assets/LH - SLATE/Trim/SPL - 254 - PNG/SPL - 254 - 18W/1-thumbnail.png",
            "full": "/assets/LH - SLATE/Trim/SPL - 254 - PNG/SPL - 254 - 18W/1.png"
          },
          {
            "thumbnail": "/assets/LH - SLATE/Trim/SPL - 254 - PNG/SPL - 254 - 18W/2-thumbnail.png",
            "full": "/assets/LH - SLATE/Trim/SPL - 254 - PNG/SPL - 254 - 18W/2.png"
          },
          {
            "thumbnail": "/assets/LH - SLATE/Trim/SPL - 254 - PNG/SPL - 254 - 18W/3-thumbnail.png",
            "full": "/assets/LH - SLATE/Trim/SPL - 254 - PNG/SPL - 254 - 18W/3.png"
          }
        ]
      }
    ]
  },
  "edge": {
    "listingThumbnail": "/assets/LL - SHARD/Edge/SPL - 155 - PNG/SPL - 155 - 3 LED - 18W 6Wx3/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "18W",
        "label": "18W",
        "images": [
          {
            "thumbnail": "/assets/LL - SHARD/Edge/SPL - 155 - PNG/SPL - 155 - 3 LED - 18W 6Wx3/1-thumbnail.png",
            "full": "/assets/LL - SHARD/Edge/SPL - 155 - PNG/SPL - 155 - 3 LED - 18W 6Wx3/1.png"
          },
          {
            "thumbnail": "/assets/LL - SHARD/Edge/SPL - 155 - PNG/SPL - 155 - 3 LED - 18W 6Wx3/2-thumbnail.png",
            "full": "/assets/LL - SHARD/Edge/SPL - 155 - PNG/SPL - 155 - 3 LED - 18W 6Wx3/2.png"
          },
          {
            "thumbnail": "/assets/LL - SHARD/Edge/SPL - 155 - PNG/SPL - 155 - 3 LED - 18W 6Wx3/3-thumbnail.png",
            "full": "/assets/LL - SHARD/Edge/SPL - 155 - PNG/SPL - 155 - 3 LED - 18W 6Wx3/3.png"
          }
        ]
      }
    ]
  },
  "phaser": {
    "listingThumbnail": "/assets/LL - SHARD/Phaser/SPL - 244 - PNG/SPL - 244 - 12W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "12W",
        "label": "12W",
        "images": [
          {
            "thumbnail": "/assets/LL - SHARD/Phaser/SPL - 244 - PNG/SPL - 244 - 12W/1-thumbnail.png",
            "full": "/assets/LL - SHARD/Phaser/SPL - 244 - PNG/SPL - 244 - 12W/1.png"
          },
          {
            "thumbnail": "/assets/LL - SHARD/Phaser/SPL - 244 - PNG/SPL - 244 - 12W/2-thumbnail.png",
            "full": "/assets/LL - SHARD/Phaser/SPL - 244 - PNG/SPL - 244 - 12W/2.png"
          },
          {
            "thumbnail": "/assets/LL - SHARD/Phaser/SPL - 244 - PNG/SPL - 244 - 12W/3-thumbnail.png",
            "full": "/assets/LL - SHARD/Phaser/SPL - 244 - PNG/SPL - 244 - 12W/3.png"
          }
        ]
      }
    ]
  },
  "prism": {
    "listingThumbnail": "/assets/LL - SHARD/Prism/SPL - 198 - PNG/SPL - 198 - WW - 12W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "12W",
        "label": "12W",
        "images": [
          {
            "thumbnail": "/assets/LL - SHARD/Prism/SPL - 198 - PNG/SPL - 198 - WW - 12W/1-thumbnail.png",
            "full": "/assets/LL - SHARD/Prism/SPL - 198 - PNG/SPL - 198 - WW - 12W/1.png"
          },
          {
            "thumbnail": "/assets/LL - SHARD/Prism/SPL - 198 - PNG/SPL - 198 - WW - 12W/2-thumbnail.png",
            "full": "/assets/LL - SHARD/Prism/SPL - 198 - PNG/SPL - 198 - WW - 12W/2.png"
          },
          {
            "thumbnail": "/assets/LL - SHARD/Prism/SPL - 198 - PNG/SPL - 198 - WW - 12W/3-thumbnail.png",
            "full": "/assets/LL - SHARD/Prism/SPL - 198 - PNG/SPL - 198 - WW - 12W/3.png"
          }
        ]
      }
    ]
  },
  "zenit": {
    "listingThumbnail": "/assets/LL - SHARD/Zenit/SPL - 235 - PNG/SPL - 235 - 12W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "12W",
        "label": "12W",
        "images": [
          {
            "thumbnail": "/assets/LL - SHARD/Zenit/SPL - 235 - PNG/SPL - 235 - 12W/1-thumbnail.png",
            "full": "/assets/LL - SHARD/Zenit/SPL - 235 - PNG/SPL - 235 - 12W/1.png"
          },
          {
            "thumbnail": "/assets/LL - SHARD/Zenit/SPL - 235 - PNG/SPL - 235 - 12W/2-thumbnail.png",
            "full": "/assets/LL - SHARD/Zenit/SPL - 235 - PNG/SPL - 235 - 12W/2.png"
          },
          {
            "thumbnail": "/assets/LL - SHARD/Zenit/SPL - 235 - PNG/SPL - 235 - 12W/3-thumbnail.png",
            "full": "/assets/LL - SHARD/Zenit/SPL - 235 - PNG/SPL - 235 - 12W/3.png"
          }
        ]
      }
    ]
  },
  "canna": {
    "listingThumbnail": "/assets/SF - CY - TORRE/Canna/SFDL-49-3RD WH 15 W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "15W",
        "label": "15W",
        "images": [
          {
            "thumbnail": "/assets/SF - CY - TORRE/Canna/SFDL-49-3RD WH 15 W/1-thumbnail.png",
            "full": "/assets/SF - CY - TORRE/Canna/SFDL-49-3RD WH 15 W/1.png"
          },
          {
            "thumbnail": "/assets/SF - CY - TORRE/Canna/SFDL-49-3RD WH 15 W/2-thumbnail.png",
            "full": "/assets/SF - CY - TORRE/Canna/SFDL-49-3RD WH 15 W/2.png"
          },
          {
            "thumbnail": "/assets/SF - CY - TORRE/Canna/SFDL-49-3RD WH 15 W/3-thumbnail.png",
            "full": "/assets/SF - CY - TORRE/Canna/SFDL-49-3RD WH 15 W/3.png"
          }
        ]
      }
    ]
  },
  "mast": {
    "listingThumbnail": "/assets/SF - CY - TORRE/Mast/SFDL-22-WH-12W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "10W",
        "label": "10W",
        "images": [
          {
            "thumbnail": "/assets/SF - CY - TORRE/Mast/SFDL-22-WH-12W/1-thumbnail.png",
            "full": "/assets/SF - CY - TORRE/Mast/SFDL-22-WH-12W/1.png"
          },
          {
            "thumbnail": "/assets/SF - CY - TORRE/Mast/SFDL-22-WH-12W/2-thumbnail.png",
            "full": "/assets/SF - CY - TORRE/Mast/SFDL-22-WH-12W/2.png"
          },
          {
            "thumbnail": "/assets/SF - CY - TORRE/Mast/SFDL-22-WH-12W/3-thumbnail.png",
            "full": "/assets/SF - CY - TORRE/Mast/SFDL-22-WH-12W/3.png"
          }
        ]
      }
    ]
  },
  "silo": {
    "listingThumbnail": "/assets/SF - CY - TORRE/Silo/SFDL-23 12W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "15W",
        "label": "15W",
        "images": [
          {
            "thumbnail": "/assets/SF - CY - TORRE/Silo/SFDL-23 12W/1-thumbnail.png",
            "full": "/assets/SF - CY - TORRE/Silo/SFDL-23 12W/1.png"
          },
          {
            "thumbnail": "/assets/SF - CY - TORRE/Silo/SFDL-23 12W/2-thumbnail.png",
            "full": "/assets/SF - CY - TORRE/Silo/SFDL-23 12W/2.png"
          },
          {
            "thumbnail": "/assets/SF - CY - TORRE/Silo/SFDL-23 12W/3-thumbnail.png",
            "full": "/assets/SF - CY - TORRE/Silo/SFDL-23 12W/3.png"
          }
        ]
      }
    ]
  },
  "stave": {
    "listingThumbnail": "/assets/SF - CY - TORRE/Stave/SFDL-43-12 W -R GOLD/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "15W",
        "label": "15W",
        "images": [
          {
            "thumbnail": "/assets/SF - CY - TORRE/Stave/SFDL-43-12 W -R GOLD/1-thumbnail.png",
            "full": "/assets/SF - CY - TORRE/Stave/SFDL-43-12 W -R GOLD/1.png"
          },
          {
            "thumbnail": "/assets/SF - CY - TORRE/Stave/SFDL-43-12 W -R GOLD/2-thumbnail.png",
            "full": "/assets/SF - CY - TORRE/Stave/SFDL-43-12 W -R GOLD/2.png"
          },
          {
            "thumbnail": "/assets/SF - CY - TORRE/Stave/SFDL-43-12 W -R GOLD/3-thumbnail.png",
            "full": "/assets/SF - CY - TORRE/Stave/SFDL-43-12 W -R GOLD/3.png"
          }
        ]
      }
    ]
  },
  "tube": {
    "listingThumbnail": "/assets/SF - CY - TORRE/Tube/SFDL-01-HAFCUT/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "10W",
        "label": "10W",
        "images": [
          {
            "thumbnail": "/assets/SF - CY - TORRE/Tube/SFDL-01-HAFCUT/1-thumbnail.png",
            "full": "/assets/SF - CY - TORRE/Tube/SFDL-01-HAFCUT/1.png"
          },
          {
            "thumbnail": "/assets/SF - CY - TORRE/Tube/SFDL-01-HAFCUT/2-thumbnail.png",
            "full": "/assets/SF - CY - TORRE/Tube/SFDL-01-HAFCUT/2.png"
          },
          {
            "thumbnail": "/assets/SF - CY - TORRE/Tube/SFDL-01-HAFCUT/3-thumbnail.png",
            "full": "/assets/SF - CY - TORRE/Tube/SFDL-01-HAFCUT/3.png"
          }
        ]
      }
    ]
  },
  "vaso": {
    "listingThumbnail": "/assets/SF - CY - TORRE/Vaso/SFDL-54-5 W GRAY/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "6W",
        "label": "6W",
        "images": [
          {
            "thumbnail": "/assets/SF - CY - TORRE/Vaso/SFDL-54-5 W GRAY/1-thumbnail.png",
            "full": "/assets/SF - CY - TORRE/Vaso/SFDL-54-5 W GRAY/1.png"
          },
          {
            "thumbnail": "/assets/SF - CY - TORRE/Vaso/SFDL-54-5 W GRAY/2-thumbnail.png",
            "full": "/assets/SF - CY - TORRE/Vaso/SFDL-54-5 W GRAY/2.png"
          },
          {
            "thumbnail": "/assets/SF - CY - TORRE/Vaso/SFDL-54-5 W GRAY/3-thumbnail.png",
            "full": "/assets/SF - CY - TORRE/Vaso/SFDL-54-5 W GRAY/3.png"
          }
        ]
      },
      {
        "wattage": "10W",
        "label": "10W",
        "images": [
          {
            "thumbnail": "/assets/SF - CY - TORRE/Vaso/SFDL-54-10 W GOLD/1-thumbnail.png",
            "full": "/assets/SF - CY - TORRE/Vaso/SFDL-54-10 W GOLD/1.png"
          },
          {
            "thumbnail": "/assets/SF - CY - TORRE/Vaso/SFDL-54-10 W GOLD/2-thumbnail.png",
            "full": "/assets/SF - CY - TORRE/Vaso/SFDL-54-10 W GOLD/2.png"
          },
          {
            "thumbnail": "/assets/SF - CY - TORRE/Vaso/SFDL-54-10 W GOLD/3-thumbnail.png",
            "full": "/assets/SF - CY - TORRE/Vaso/SFDL-54-10 W GOLD/3.png"
          }
        ]
      },
      {
        "wattage": "15W",
        "label": "15W",
        "images": [
          {
            "thumbnail": "/assets/SF - CY - TORRE/Vaso/SFDL-54-15 W R GOLD/1-thumbnail.png",
            "full": "/assets/SF - CY - TORRE/Vaso/SFDL-54-15 W R GOLD/1.png"
          },
          {
            "thumbnail": "/assets/SF - CY - TORRE/Vaso/SFDL-54-15 W R GOLD/2-thumbnail.png",
            "full": "/assets/SF - CY - TORRE/Vaso/SFDL-54-15 W R GOLD/2.png"
          },
          {
            "thumbnail": "/assets/SF - CY - TORRE/Vaso/SFDL-54-15 W R GOLD/3-thumbnail.png",
            "full": "/assets/SF - CY - TORRE/Vaso/SFDL-54-15 W R GOLD/3.png"
          }
        ]
      }
    ]
  },
  "binova": {
    "listingThumbnail": "/assets/SF - DO - DUO/Binova/SFDL-40-DBL-WH-24W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "12 x 2W",
        "label": "12 x 2W",
        "images": [
          {
            "thumbnail": "/assets/SF - DO - DUO/Binova/SFDL-40-DBL-WH-24W/1-thumbnail.png",
            "full": "/assets/SF - DO - DUO/Binova/SFDL-40-DBL-WH-24W/1.png"
          },
          {
            "thumbnail": "/assets/SF - DO - DUO/Binova/SFDL-40-DBL-WH-24W/2-thumbnail.png",
            "full": "/assets/SF - DO - DUO/Binova/SFDL-40-DBL-WH-24W/2.png"
          },
          {
            "thumbnail": "/assets/SF - DO - DUO/Binova/SFDL-40-DBL-WH-24W/3-thumbnail.png",
            "full": "/assets/SF - DO - DUO/Binova/SFDL-40-DBL-WH-24W/3.png"
          }
        ]
      }
    ]
  },
  "diplex": {
    "listingThumbnail": "/assets/SF - DO - DUO/Diplex/SFDL-29-BK24W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "15 x 2W",
        "label": "15 x 2W",
        "images": [
          {
            "thumbnail": "/assets/SF - DO - DUO/Diplex/SFDL-29-BK24W/1-thumbnail.png",
            "full": "/assets/SF - DO - DUO/Diplex/SFDL-29-BK24W/1.png"
          },
          {
            "thumbnail": "/assets/SF - DO - DUO/Diplex/SFDL-29-BK24W/2-thumbnail.png",
            "full": "/assets/SF - DO - DUO/Diplex/SFDL-29-BK24W/2.png"
          },
          {
            "thumbnail": "/assets/SF - DO - DUO/Diplex/SFDL-29-BK24W/3-thumbnail.png",
            "full": "/assets/SF - DO - DUO/Diplex/SFDL-29-BK24W/3.png"
          }
        ]
      }
    ]
  },
  "dival": {
    "listingThumbnail": "/assets/SF - DO - DUO/Dival/SFDL-43-12x2-GOLD/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "12 x 2W",
        "label": "12 x 2W",
        "images": [
          {
            "thumbnail": "/assets/SF - DO - DUO/Dival/SFDL-43-12x2-GOLD/1-thumbnail.png",
            "full": "/assets/SF - DO - DUO/Dival/SFDL-43-12x2-GOLD/1.png"
          },
          {
            "thumbnail": "/assets/SF - DO - DUO/Dival/SFDL-43-12x2-GOLD/2-thumbnail.png",
            "full": "/assets/SF - DO - DUO/Dival/SFDL-43-12x2-GOLD/2.png"
          },
          {
            "thumbnail": "/assets/SF - DO - DUO/Dival/SFDL-43-12x2-GOLD/3-thumbnail.png",
            "full": "/assets/SF - DO - DUO/Dival/SFDL-43-12x2-GOLD/3.png"
          }
        ]
      }
    ]
  },
  "descent": {
    "listingThumbnail": "/assets/SF - HG - DRAPE/Descent/SFDC-33-BK-8W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "3 + 5W",
        "label": "3 + 5W",
        "images": [
          {
            "thumbnail": "/assets/SF - HG - DRAPE/Descent/SFDC-33-BK-8W/1-thumbnail.png",
            "full": "/assets/SF - HG - DRAPE/Descent/SFDC-33-BK-8W/1.png"
          },
          {
            "thumbnail": "/assets/SF - HG - DRAPE/Descent/SFDC-33-BK-8W/2-thumbnail.png",
            "full": "/assets/SF - HG - DRAPE/Descent/SFDC-33-BK-8W/2.png"
          },
          {
            "thumbnail": "/assets/SF - HG - DRAPE/Descent/SFDC-33-BK-8W/3-thumbnail.png",
            "full": "/assets/SF - HG - DRAPE/Descent/SFDC-33-BK-8W/3.png"
          },
          {
            "thumbnail": "/assets/SF - HG - DRAPE/Descent/SFDC-33-BK-8W/4-thumbnail.png",
            "full": "/assets/SF - HG - DRAPE/Descent/SFDC-33-BK-8W/4.png"
          }
        ]
      }
    ]
  },
  "pendulo": {
    "listingThumbnail": "/assets/SF - HG - DRAPE/Pendulo/SFDL-37 R GOLD 8W/Lights9707 copy 2-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "10W",
        "label": "10W",
        "images": [
          {
            "thumbnail": "/assets/SF - HG - DRAPE/Pendulo/SFDL-37 R GOLD 8W/Lights9707 copy 2-thumbnail.png",
            "full": "/assets/SF - HG - DRAPE/Pendulo/SFDL-37 R GOLD 8W/Lights9707 copy 2.png"
          },
          {
            "thumbnail": "/assets/SF - HG - DRAPE/Pendulo/SFDL-37 R GOLD 8W/Lights9710 copy 2-thumbnail.png",
            "full": "/assets/SF - HG - DRAPE/Pendulo/SFDL-37 R GOLD 8W/Lights9710 copy 2.png"
          },
          {
            "thumbnail": "/assets/SF - HG - DRAPE/Pendulo/SFDL-37 R GOLD 8W/Lights9713 copy 2-thumbnail.png",
            "full": "/assets/SF - HG - DRAPE/Pendulo/SFDL-37 R GOLD 8W/Lights9713 copy 2.png"
          }
        ]
      }
    ]
  },
  "tine": {
    "listingThumbnail": "/assets/SF - LZ - BLADE/Tine/SFDL-39-WH-12W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "12–15W",
        "label": "12–15W",
        "images": [
          {
            "thumbnail": "/assets/SF - LZ - BLADE/Tine/SFDL-39-WH-12W/1-thumbnail.png",
            "full": "/assets/SF - LZ - BLADE/Tine/SFDL-39-WH-12W/1.png"
          },
          {
            "thumbnail": "/assets/SF - LZ - BLADE/Tine/SFDL-39-WH-12W/2-thumbnail.png",
            "full": "/assets/SF - LZ - BLADE/Tine/SFDL-39-WH-12W/2.png"
          },
          {
            "thumbnail": "/assets/SF - LZ - BLADE/Tine/SFDL-39-WH-12W/3-thumbnail.png",
            "full": "/assets/SF - LZ - BLADE/Tine/SFDL-39-WH-12W/3.png"
          }
        ]
      }
    ]
  },
  "helm": {
    "listingThumbnail": "/assets/SF - MV - FLEX/Helm/SFDL-47-BK-10W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "8W",
        "label": "8W",
        "images": [
          {
            "thumbnail": "/assets/SF - MV - FLEX/Helm/SFDL-47-BK-10W/1-thumbnail.png",
            "full": "/assets/SF - MV - FLEX/Helm/SFDL-47-BK-10W/1.png"
          }
        ]
      }
    ]
  },
  "pivot": {
    "listingThumbnail": "/assets/SF - MV - FLEX/Pivot/SFDL-14-S.B 12 W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "12W",
        "label": "12W",
        "images": [
          {
            "thumbnail": "/assets/SF - MV - FLEX/Pivot/SFDL-14-S.B 12 W/1-thumbnail.png",
            "full": "/assets/SF - MV - FLEX/Pivot/SFDL-14-S.B 12 W/1.png"
          },
          {
            "thumbnail": "/assets/SF - MV - FLEX/Pivot/SFDL-14-S.B 12 W/2-thumbnail.png",
            "full": "/assets/SF - MV - FLEX/Pivot/SFDL-14-S.B 12 W/2.png"
          },
          {
            "thumbnail": "/assets/SF - MV - FLEX/Pivot/SFDL-14-S.B 12 W/3-thumbnail.png",
            "full": "/assets/SF - MV - FLEX/Pivot/SFDL-14-S.B 12 W/3.png"
          }
        ]
      }
    ]
  },
  "rotar": {
    "listingThumbnail": "/assets/SF - MV - FLEX/Rotar/SFDL-41-BK/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "6W",
        "label": "6W",
        "images": [
          {
            "thumbnail": "/assets/SF - MV - FLEX/Rotar/SFDL-41-BK/1-thumbnail.png",
            "full": "/assets/SF - MV - FLEX/Rotar/SFDL-41-BK/1.png"
          },
          {
            "thumbnail": "/assets/SF - MV - FLEX/Rotar/SFDL-41-BK/2-thumbnail.png",
            "full": "/assets/SF - MV - FLEX/Rotar/SFDL-41-BK/2.png"
          },
          {
            "thumbnail": "/assets/SF - MV - FLEX/Rotar/SFDL-41-BK/3-thumbnail.png",
            "full": "/assets/SF - MV - FLEX/Rotar/SFDL-41-BK/3.png"
          }
        ]
      }
    ]
  },
  "swivel": {
    "listingThumbnail": "/assets/SF - MV - FLEX/Swivel/SFDL- 17-BK-5W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "5W",
        "label": "5W",
        "images": [
          {
            "thumbnail": "/assets/SF - MV - FLEX/Swivel/SFDL- 17-BK-5W/1-thumbnail.png",
            "full": "/assets/SF - MV - FLEX/Swivel/SFDL- 17-BK-5W/1.png"
          },
          {
            "thumbnail": "/assets/SF - MV - FLEX/Swivel/SFDL- 17-BK-5W/2-thumbnail.png",
            "full": "/assets/SF - MV - FLEX/Swivel/SFDL- 17-BK-5W/2.png"
          },
          {
            "thumbnail": "/assets/SF - MV - FLEX/Swivel/SFDL- 17-BK-5W/3-thumbnail.png",
            "full": "/assets/SF - MV - FLEX/Swivel/SFDL- 17-BK-5W/3.png"
          }
        ]
      }
    ]
  },
  "tiltable": {
    "listingThumbnail": "/assets/SF - MV - FLEX/Tiltable/SFDL - 18/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "12W",
        "label": "12W",
        "images": [
          {
            "thumbnail": "/assets/SF - MV - FLEX/Tiltable/SFDL - 18/1-thumbnail.png",
            "full": "/assets/SF - MV - FLEX/Tiltable/SFDL - 18/1.png"
          },
          {
            "thumbnail": "/assets/SF - MV - FLEX/Tiltable/SFDL - 18/2-thumbnail.png",
            "full": "/assets/SF - MV - FLEX/Tiltable/SFDL - 18/2.png"
          },
          {
            "thumbnail": "/assets/SF - MV - FLEX/Tiltable/SFDL - 18/3-thumbnail.png",
            "full": "/assets/SF - MV - FLEX/Tiltable/SFDL - 18/3.png"
          },
          {
            "thumbnail": "/assets/SF - MV - FLEX/Tiltable/SFDL - 18/4-thumbnail.png",
            "full": "/assets/SF - MV - FLEX/Tiltable/SFDL - 18/4.png"
          }
        ]
      }
    ]
  },
  "turn": {
    "listingThumbnail": "/assets/SF - MV - FLEX/Turn/SFDL-25-6 W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "5W",
        "label": "5W",
        "images": [
          {
            "thumbnail": "/assets/SF - MV - FLEX/Turn/SFDL-25-6 W/1-thumbnail.png",
            "full": "/assets/SF - MV - FLEX/Turn/SFDL-25-6 W/1.png"
          },
          {
            "thumbnail": "/assets/SF - MV - FLEX/Turn/SFDL-25-6 W/2-thumbnail.png",
            "full": "/assets/SF - MV - FLEX/Turn/SFDL-25-6 W/2.png"
          },
          {
            "thumbnail": "/assets/SF - MV - FLEX/Turn/SFDL-25-6 W/3-thumbnail.png",
            "full": "/assets/SF - MV - FLEX/Turn/SFDL-25-6 W/3.png"
          }
        ]
      }
    ]
  },
  "rimless-round": {
    "listingThumbnail": "/assets/SF - RM - SHEER/Rimless Round/SURFACE DORNLIGHT RIMLENS ROUND (W)/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "SURFACE DORNLIGHT RIMLENS ROUND (W)",
        "label": "SURFACE DORNLIGHT RIMLENS ROUND (W)",
        "images": [
          {
            "thumbnail": "/assets/SF - RM - SHEER/Rimless Round/SURFACE DORNLIGHT RIMLENS ROUND (W)/1-thumbnail.png",
            "full": "/assets/SF - RM - SHEER/Rimless Round/SURFACE DORNLIGHT RIMLENS ROUND (W)/1.png"
          },
          {
            "thumbnail": "/assets/SF - RM - SHEER/Rimless Round/SURFACE DORNLIGHT RIMLENS ROUND (W)/2-thumbnail.png",
            "full": "/assets/SF - RM - SHEER/Rimless Round/SURFACE DORNLIGHT RIMLENS ROUND (W)/2.png"
          }
        ]
      }
    ]
  },
  "rimless-square": {
    "listingThumbnail": "/assets/SF - RM - SHEER/Rimless Square/SURFACE DOWNLIGHT SQUARE PIMLESS WH/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "SURFACE DOWNLIGHT SQUARE PIMLESS WH",
        "label": "SURFACE DOWNLIGHT SQUARE PIMLESS WH",
        "images": [
          {
            "thumbnail": "/assets/SF - RM - SHEER/Rimless Square/SURFACE DOWNLIGHT SQUARE PIMLESS WH/1-thumbnail.png",
            "full": "/assets/SF - RM - SHEER/Rimless Square/SURFACE DOWNLIGHT SQUARE PIMLESS WH/1.png"
          },
          {
            "thumbnail": "/assets/SF - RM - SHEER/Rimless Square/SURFACE DOWNLIGHT SQUARE PIMLESS WH/2-thumbnail.png",
            "full": "/assets/SF - RM - SHEER/Rimless Square/SURFACE DOWNLIGHT SQUARE PIMLESS WH/2.png"
          },
          {
            "thumbnail": "/assets/SF - RM - SHEER/Rimless Square/SURFACE DOWNLIGHT SQUARE PIMLESS WH/3-thumbnail.png",
            "full": "/assets/SF - RM - SHEER/Rimless Square/SURFACE DOWNLIGHT SQUARE PIMLESS WH/3.png"
          }
        ]
      }
    ]
  },
  "sweep": {
    "listingThumbnail": "/assets/SF - SW - MURAL/Sweep/SFDL-44 BK 6 W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "9W",
        "label": "9W",
        "images": [
          {
            "thumbnail": "/assets/SF - SW - MURAL/Sweep/SFDL-44 BK 6 W/1-thumbnail.png",
            "full": "/assets/SF - SW - MURAL/Sweep/SFDL-44 BK 6 W/1.png"
          },
          {
            "thumbnail": "/assets/SF - SW - MURAL/Sweep/SFDL-44 BK 6 W/2-thumbnail.png",
            "full": "/assets/SF - SW - MURAL/Sweep/SFDL-44 BK 6 W/2.png"
          },
          {
            "thumbnail": "/assets/SF - SW - MURAL/Sweep/SFDL-44 BK 6 W/3-thumbnail.png",
            "full": "/assets/SF - SW - MURAL/Sweep/SFDL-44 BK 6 W/3.png"
          }
        ]
      }
    ]
  },
  "acute": {
    "listingThumbnail": "/assets/SN - FINO/Acute/SPL - 205 - PNG/SPL - 205 - 20W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "20W",
        "label": "20W",
        "images": [
          {
            "thumbnail": "/assets/SN - FINO/Acute/SPL - 205 - PNG/SPL - 205 - 20W/1-thumbnail.png",
            "full": "/assets/SN - FINO/Acute/SPL - 205 - PNG/SPL - 205 - 20W/1.png"
          },
          {
            "thumbnail": "/assets/SN - FINO/Acute/SPL - 205 - PNG/SPL - 205 - 20W/2-thumbnail.png",
            "full": "/assets/SN - FINO/Acute/SPL - 205 - PNG/SPL - 205 - 20W/2.png"
          },
          {
            "thumbnail": "/assets/SN - FINO/Acute/SPL - 205 - PNG/SPL - 205 - 20W/3-thumbnail.png",
            "full": "/assets/SN - FINO/Acute/SPL - 205 - PNG/SPL - 205 - 20W/3.png"
          }
        ]
      }
    ]
  },
  "narrow": {
    "listingThumbnail": "/assets/SN - FINO/Narrow/SPL - 211 - PNG/SPL - 211 - 1&1 - 7W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "7W",
        "label": "7W",
        "images": [
          {
            "thumbnail": "/assets/SN - FINO/Narrow/SPL - 211 - PNG/SPL - 211 - 1&1 - 7W/1-thumbnail.png",
            "full": "/assets/SN - FINO/Narrow/SPL - 211 - PNG/SPL - 211 - 1&1 - 7W/1.png"
          },
          {
            "thumbnail": "/assets/SN - FINO/Narrow/SPL - 211 - PNG/SPL - 211 - 1&1 - 7W/2-thumbnail.png",
            "full": "/assets/SN - FINO/Narrow/SPL - 211 - PNG/SPL - 211 - 1&1 - 7W/2.png"
          },
          {
            "thumbnail": "/assets/SN - FINO/Narrow/SPL - 211 - PNG/SPL - 211 - 1&1 - 7W/3-thumbnail.png",
            "full": "/assets/SN - FINO/Narrow/SPL - 211 - PNG/SPL - 211 - 1&1 - 7W/3.png"
          }
        ]
      },
      {
        "wattage": "10W",
        "label": "10W",
        "images": [
          {
            "thumbnail": "/assets/SN - FINO/Narrow/SPL - 211 - PNG/SPL - 211 - 2ND - BK - 10W/1-thumbnail.png",
            "full": "/assets/SN - FINO/Narrow/SPL - 211 - PNG/SPL - 211 - 2ND - BK - 10W/1.png"
          },
          {
            "thumbnail": "/assets/SN - FINO/Narrow/SPL - 211 - PNG/SPL - 211 - 2ND - BK - 10W/2-thumbnail.png",
            "full": "/assets/SN - FINO/Narrow/SPL - 211 - PNG/SPL - 211 - 2ND - BK - 10W/2.png"
          },
          {
            "thumbnail": "/assets/SN - FINO/Narrow/SPL - 211 - PNG/SPL - 211 - 2ND - BK - 10W/3-thumbnail.png",
            "full": "/assets/SN - FINO/Narrow/SPL - 211 - PNG/SPL - 211 - 2ND - BK - 10W/3.png"
          }
        ]
      },
      {
        "wattage": "12W",
        "label": "12W",
        "images": [
          {
            "thumbnail": "/assets/SN - FINO/Narrow/SPL - 211 - PNG/SPL - 211 - 3RD - 12W/1-thumbnail.png",
            "full": "/assets/SN - FINO/Narrow/SPL - 211 - PNG/SPL - 211 - 3RD - 12W/1.png"
          },
          {
            "thumbnail": "/assets/SN - FINO/Narrow/SPL - 211 - PNG/SPL - 211 - 3RD - 12W/2-thumbnail.png",
            "full": "/assets/SN - FINO/Narrow/SPL - 211 - PNG/SPL - 211 - 3RD - 12W/2.png"
          },
          {
            "thumbnail": "/assets/SN - FINO/Narrow/SPL - 211 - PNG/SPL - 211 - 3RD - 12W/3-thumbnail.png",
            "full": "/assets/SN - FINO/Narrow/SPL - 211 - PNG/SPL - 211 - 3RD - 12W/3.png"
          }
        ]
      },
      {
        "wattage": "16W",
        "label": "16W",
        "images": [
          {
            "thumbnail": "/assets/SN - FINO/Narrow/SPL - 211 - PNG/SPL - 211 - 4TH - 16W/1-thumbnail.png",
            "full": "/assets/SN - FINO/Narrow/SPL - 211 - PNG/SPL - 211 - 4TH - 16W/1.png"
          },
          {
            "thumbnail": "/assets/SN - FINO/Narrow/SPL - 211 - PNG/SPL - 211 - 4TH - 16W/2-thumbnail.png",
            "full": "/assets/SN - FINO/Narrow/SPL - 211 - PNG/SPL - 211 - 4TH - 16W/2.png"
          },
          {
            "thumbnail": "/assets/SN - FINO/Narrow/SPL - 211 - PNG/SPL - 211 - 4TH - 16W/3-thumbnail.png",
            "full": "/assets/SN - FINO/Narrow/SPL - 211 - PNG/SPL - 211 - 4TH - 16W/3.png"
          }
        ]
      }
    ]
  },
  "taper": {
    "listingThumbnail": "/assets/SN - FINO/Taper/SPL - 208 - PNG/SPL - 208 - 1&1 - 7W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "7W",
        "label": "7W",
        "images": [
          {
            "thumbnail": "/assets/SN - FINO/Taper/SPL - 208 - PNG/SPL - 208 - 1&1 - 7W/1-thumbnail.png",
            "full": "/assets/SN - FINO/Taper/SPL - 208 - PNG/SPL - 208 - 1&1 - 7W/1.png"
          },
          {
            "thumbnail": "/assets/SN - FINO/Taper/SPL - 208 - PNG/SPL - 208 - 1&1 - 7W/2-thumbnail.png",
            "full": "/assets/SN - FINO/Taper/SPL - 208 - PNG/SPL - 208 - 1&1 - 7W/2.png"
          },
          {
            "thumbnail": "/assets/SN - FINO/Taper/SPL - 208 - PNG/SPL - 208 - 1&1 - 7W/3-thumbnail.png",
            "full": "/assets/SN - FINO/Taper/SPL - 208 - PNG/SPL - 208 - 1&1 - 7W/3.png"
          }
        ]
      },
      {
        "wattage": "10W",
        "label": "10W",
        "images": [
          {
            "thumbnail": "/assets/SN - FINO/Taper/SPL - 208 - PNG/SPL - 208 - 2ND - 10W/1-thumbnail.png",
            "full": "/assets/SN - FINO/Taper/SPL - 208 - PNG/SPL - 208 - 2ND - 10W/1.png"
          },
          {
            "thumbnail": "/assets/SN - FINO/Taper/SPL - 208 - PNG/SPL - 208 - 2ND - 10W/2-thumbnail.png",
            "full": "/assets/SN - FINO/Taper/SPL - 208 - PNG/SPL - 208 - 2ND - 10W/2.png"
          },
          {
            "thumbnail": "/assets/SN - FINO/Taper/SPL - 208 - PNG/SPL - 208 - 2ND - 10W/3-thumbnail.png",
            "full": "/assets/SN - FINO/Taper/SPL - 208 - PNG/SPL - 208 - 2ND - 10W/3.png"
          }
        ]
      },
      {
        "wattage": "14W",
        "label": "14W",
        "images": [
          {
            "thumbnail": "/assets/SN - FINO/Taper/SPL - 208 - PNG/SPL - 208 - 3RD - 14W/1-thumbnail.png",
            "full": "/assets/SN - FINO/Taper/SPL - 208 - PNG/SPL - 208 - 3RD - 14W/1.png"
          },
          {
            "thumbnail": "/assets/SN - FINO/Taper/SPL - 208 - PNG/SPL - 208 - 3RD - 14W/2-thumbnail.png",
            "full": "/assets/SN - FINO/Taper/SPL - 208 - PNG/SPL - 208 - 3RD - 14W/2.png"
          },
          {
            "thumbnail": "/assets/SN - FINO/Taper/SPL - 208 - PNG/SPL - 208 - 3RD - 14W/3-thumbnail.png",
            "full": "/assets/SN - FINO/Taper/SPL - 208 - PNG/SPL - 208 - 3RD - 14W/3.png"
          }
        ]
      },
      {
        "wattage": "22W",
        "label": "22W",
        "images": [
          {
            "thumbnail": "/assets/SN - FINO/Taper/SPL - 208 - PNG/SPL - 208 - 5TH - 22W/1-thumbnail.png",
            "full": "/assets/SN - FINO/Taper/SPL - 208 - PNG/SPL - 208 - 5TH - 22W/1.png"
          },
          {
            "thumbnail": "/assets/SN - FINO/Taper/SPL - 208 - PNG/SPL - 208 - 5TH - 22W/2-thumbnail.png",
            "full": "/assets/SN - FINO/Taper/SPL - 208 - PNG/SPL - 208 - 5TH - 22W/2.png"
          },
          {
            "thumbnail": "/assets/SN - FINO/Taper/SPL - 208 - PNG/SPL - 208 - 5TH - 22W/3-thumbnail.png",
            "full": "/assets/SN - FINO/Taper/SPL - 208 - PNG/SPL - 208 - 5TH - 22W/3.png"
          }
        ]
      }
    ]
  },
  "thread": {
    "listingThumbnail": "/assets/SN - FINO/Thread/SPL - 191 - PNG/SPL - 191 - 4th - 15W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "15W",
        "label": "15W",
        "images": [
          {
            "thumbnail": "/assets/SN - FINO/Thread/SPL - 191 - PNG/SPL - 191 - 4th - 15W/1-thumbnail.png",
            "full": "/assets/SN - FINO/Thread/SPL - 191 - PNG/SPL - 191 - 4th - 15W/1.png"
          },
          {
            "thumbnail": "/assets/SN - FINO/Thread/SPL - 191 - PNG/SPL - 191 - 4th - 15W/2-thumbnail.png",
            "full": "/assets/SN - FINO/Thread/SPL - 191 - PNG/SPL - 191 - 4th - 15W/2.png"
          },
          {
            "thumbnail": "/assets/SN - FINO/Thread/SPL - 191 - PNG/SPL - 191 - 4th - 15W/3-thumbnail.png",
            "full": "/assets/SN - FINO/Thread/SPL - 191 - PNG/SPL - 191 - 4th - 15W/3.png"
          }
        ]
      }
    ]
  },
  "seamless": {
    "listingThumbnail": "/assets/TL - FLUSH/Seamless/SPL - 273 - PNG/SPL - 273 - 8W - WH/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "8W",
        "label": "8W",
        "images": [
          {
            "thumbnail": "/assets/TL - FLUSH/Seamless/SPL - 273 - PNG/SPL - 273 - 8W - WH/1-thumbnail.png",
            "full": "/assets/TL - FLUSH/Seamless/SPL - 273 - PNG/SPL - 273 - 8W - WH/1.png"
          },
          {
            "thumbnail": "/assets/TL - FLUSH/Seamless/SPL - 273 - PNG/SPL - 273 - 8W - WH/2-thumbnail.png",
            "full": "/assets/TL - FLUSH/Seamless/SPL - 273 - PNG/SPL - 273 - 8W - WH/2.png"
          },
          {
            "thumbnail": "/assets/TL - FLUSH/Seamless/SPL - 273 - PNG/SPL - 273 - 8W - WH/3-thumbnail.png",
            "full": "/assets/TL - FLUSH/Seamless/SPL - 273 - PNG/SPL - 273 - 8W - WH/3.png"
          }
        ]
      },
      {
        "wattage": "12W",
        "label": "12W",
        "images": [
          {
            "thumbnail": "/assets/TL - FLUSH/Seamless/SPL - 273 - PNG/SPL - 273 - 12W - GMB/1-thumbnail.png",
            "full": "/assets/TL - FLUSH/Seamless/SPL - 273 - PNG/SPL - 273 - 12W - GMB/1.png"
          },
          {
            "thumbnail": "/assets/TL - FLUSH/Seamless/SPL - 273 - PNG/SPL - 273 - 12W - GMB/2-thumbnail.png",
            "full": "/assets/TL - FLUSH/Seamless/SPL - 273 - PNG/SPL - 273 - 12W - GMB/2.png"
          },
          {
            "thumbnail": "/assets/TL - FLUSH/Seamless/SPL - 273 - PNG/SPL - 273 - 12W - GMB/3-thumbnail.png",
            "full": "/assets/TL - FLUSH/Seamless/SPL - 273 - PNG/SPL - 273 - 12W - GMB/3.png"
          }
        ]
      },
      {
        "wattage": "15W",
        "label": "15W",
        "images": [
          {
            "thumbnail": "/assets/TL - FLUSH/Seamless/SPL - 273 - PNG/SPL - 273 - 15W - WH/1-thumbnail.png",
            "full": "/assets/TL - FLUSH/Seamless/SPL - 273 - PNG/SPL - 273 - 15W - WH/1.png"
          },
          {
            "thumbnail": "/assets/TL - FLUSH/Seamless/SPL - 273 - PNG/SPL - 273 - 15W - WH/2-thumbnail.png",
            "full": "/assets/TL - FLUSH/Seamless/SPL - 273 - PNG/SPL - 273 - 15W - WH/2.png"
          },
          {
            "thumbnail": "/assets/TL - FLUSH/Seamless/SPL - 273 - PNG/SPL - 273 - 15W - WH/3-thumbnail.png",
            "full": "/assets/TL - FLUSH/Seamless/SPL - 273 - PNG/SPL - 273 - 15W - WH/3.png"
          }
        ]
      }
    ]
  },
  "void": {
    "listingThumbnail": "/assets/TL - FLUSH/Void/SPL - 272 - PNG/SPL - 272 - 5W - WH/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "5W",
        "label": "5W",
        "images": [
          {
            "thumbnail": "/assets/TL - FLUSH/Void/SPL - 272 - PNG/SPL - 272 - 5W - WH/1-thumbnail.png",
            "full": "/assets/TL - FLUSH/Void/SPL - 272 - PNG/SPL - 272 - 5W - WH/1.png"
          },
          {
            "thumbnail": "/assets/TL - FLUSH/Void/SPL - 272 - PNG/SPL - 272 - 5W - WH/2-thumbnail.png",
            "full": "/assets/TL - FLUSH/Void/SPL - 272 - PNG/SPL - 272 - 5W - WH/2.png"
          },
          {
            "thumbnail": "/assets/TL - FLUSH/Void/SPL - 272 - PNG/SPL - 272 - 5W - WH/3-thumbnail.png",
            "full": "/assets/TL - FLUSH/Void/SPL - 272 - PNG/SPL - 272 - 5W - WH/3.png"
          }
        ]
      },
      {
        "wattage": "8W",
        "label": "8W",
        "images": [
          {
            "thumbnail": "/assets/TL - FLUSH/Void/SPL - 272 - PNG/SPL - 272 - 8W - GMB/1-thumbnail.png",
            "full": "/assets/TL - FLUSH/Void/SPL - 272 - PNG/SPL - 272 - 8W - GMB/1.png"
          },
          {
            "thumbnail": "/assets/TL - FLUSH/Void/SPL - 272 - PNG/SPL - 272 - 8W - GMB/2-thumbnail.png",
            "full": "/assets/TL - FLUSH/Void/SPL - 272 - PNG/SPL - 272 - 8W - GMB/2.png"
          },
          {
            "thumbnail": "/assets/TL - FLUSH/Void/SPL - 272 - PNG/SPL - 272 - 8W - GMB/3-thumbnail.png",
            "full": "/assets/TL - FLUSH/Void/SPL - 272 - PNG/SPL - 272 - 8W - GMB/3.png"
          }
        ]
      },
      {
        "wattage": "10W",
        "label": "10W",
        "images": [
          {
            "thumbnail": "/assets/TL - FLUSH/Void/SPL - 272 - PNG/SPL - 272 - 10W - WH/1-thumbnail.png",
            "full": "/assets/TL - FLUSH/Void/SPL - 272 - PNG/SPL - 272 - 10W - WH/1.png"
          },
          {
            "thumbnail": "/assets/TL - FLUSH/Void/SPL - 272 - PNG/SPL - 272 - 10W - WH/2-thumbnail.png",
            "full": "/assets/TL - FLUSH/Void/SPL - 272 - PNG/SPL - 272 - 10W - WH/2.png"
          },
          {
            "thumbnail": "/assets/TL - FLUSH/Void/SPL - 272 - PNG/SPL - 272 - 10W - WH/3-thumbnail.png",
            "full": "/assets/TL - FLUSH/Void/SPL - 272 - PNG/SPL - 272 - 10W - WH/3.png"
          }
        ]
      },
      {
        "wattage": "12W",
        "label": "12W",
        "images": [
          {
            "thumbnail": "/assets/TL - FLUSH/Void/SPL - 272 - PNG/SPL - 272 - 15W - GMB/1-thumbnail.png",
            "full": "/assets/TL - FLUSH/Void/SPL - 272 - PNG/SPL - 272 - 15W - GMB/1.png"
          },
          {
            "thumbnail": "/assets/TL - FLUSH/Void/SPL - 272 - PNG/SPL - 272 - 15W - GMB/3-thumbnail.png",
            "full": "/assets/TL - FLUSH/Void/SPL - 272 - PNG/SPL - 272 - 15W - GMB/3.png"
          }
        ]
      }
    ]
  },
  "drift": {
    "listingThumbnail": "/assets/WW - FRESCO/Drift/SPL - 209 - PNG/SPL - 209 - 12(W)/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "12W",
        "label": "12W",
        "images": [
          {
            "thumbnail": "/assets/WW - FRESCO/Drift/SPL - 209 - PNG/SPL - 209 - 12(W)/1-thumbnail.png",
            "full": "/assets/WW - FRESCO/Drift/SPL - 209 - PNG/SPL - 209 - 12(W)/1.png"
          },
          {
            "thumbnail": "/assets/WW - FRESCO/Drift/SPL - 209 - PNG/SPL - 209 - 12(W)/2-thumbnail.png",
            "full": "/assets/WW - FRESCO/Drift/SPL - 209 - PNG/SPL - 209 - 12(W)/2.png"
          },
          {
            "thumbnail": "/assets/WW - FRESCO/Drift/SPL - 209 - PNG/SPL - 209 - 12(W)/3-thumbnail.png",
            "full": "/assets/WW - FRESCO/Drift/SPL - 209 - PNG/SPL - 209 - 12(W)/3.png"
          }
        ]
      }
    ]
  },
  "glide": {
    "listingThumbnail": "/assets/WW - FRESCO/Glide/SPL - 193 - PNG/SPL - 193 - 10W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "10W",
        "label": "10W",
        "images": [
          {
            "thumbnail": "/assets/WW - FRESCO/Glide/SPL - 193 - PNG/SPL - 193 - 10W/1-thumbnail.png",
            "full": "/assets/WW - FRESCO/Glide/SPL - 193 - PNG/SPL - 193 - 10W/1.png"
          },
          {
            "thumbnail": "/assets/WW - FRESCO/Glide/SPL - 193 - PNG/SPL - 193 - 10W/2-thumbnail.png",
            "full": "/assets/WW - FRESCO/Glide/SPL - 193 - PNG/SPL - 193 - 10W/2.png"
          },
          {
            "thumbnail": "/assets/WW - FRESCO/Glide/SPL - 193 - PNG/SPL - 193 - 10W/3-thumbnail.png",
            "full": "/assets/WW - FRESCO/Glide/SPL - 193 - PNG/SPL - 193 - 10W/3.png"
          }
        ]
      }
    ]
  },
  "graze": {
    "listingThumbnail": "/assets/WW - FRESCO/Graze/SPL - 243 - PNG/SPL - 243 - 12W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "12W",
        "label": "12W",
        "images": [
          {
            "thumbnail": "/assets/WW - FRESCO/Graze/SPL - 243 - PNG/SPL - 243 - 12W/1-thumbnail.png",
            "full": "/assets/WW - FRESCO/Graze/SPL - 243 - PNG/SPL - 243 - 12W/1.png"
          },
          {
            "thumbnail": "/assets/WW - FRESCO/Graze/SPL - 243 - PNG/SPL - 243 - 12W/2-thumbnail.png",
            "full": "/assets/WW - FRESCO/Graze/SPL - 243 - PNG/SPL - 243 - 12W/2.png"
          },
          {
            "thumbnail": "/assets/WW - FRESCO/Graze/SPL - 243 - PNG/SPL - 243 - 12W/3-thumbnail.png",
            "full": "/assets/WW - FRESCO/Graze/SPL - 243 - PNG/SPL - 243 - 12W/3.png"
          }
        ]
      }
    ]
  },
  "wave": {
    "listingThumbnail": "/assets/WW - FRESCO/Wave/SPL - 239 - PNG/SPL - 239 - 12W/1-thumbnail.png",
    "wattVariants": [
      {
        "wattage": "12W",
        "label": "12W",
        "images": [
          {
            "thumbnail": "/assets/WW - FRESCO/Wave/SPL - 239 - PNG/SPL - 239 - 12W/1-thumbnail.png",
            "full": "/assets/WW - FRESCO/Wave/SPL - 239 - PNG/SPL - 239 - 12W/1.png"
          },
          {
            "thumbnail": "/assets/WW - FRESCO/Wave/SPL - 239 - PNG/SPL - 239 - 12W/2-thumbnail.png",
            "full": "/assets/WW - FRESCO/Wave/SPL - 239 - PNG/SPL - 239 - 12W/2.png"
          },
          {
            "thumbnail": "/assets/WW - FRESCO/Wave/SPL - 239 - PNG/SPL - 239 - 12W/3-thumbnail.png",
            "full": "/assets/WW - FRESCO/Wave/SPL - 239 - PNG/SPL - 239 - 12W/3.png"
          }
        ]
      }
    ]
  }
};
